### ISSUE TITLE
Broken links to blog article about error logs

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-website#1272]
## Where to find the issue

https://www.coronawarn.app/de/faq/#error_log
## Describe the issue

Your FAQ for the new function "error logs" gives two links to blog articles on this function, but they are broken.

Note: The broken link is https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2//
 I get a 404

## Suggested change

Correct the links

**Comment by MikeMcC399** [comment]
@ndegendogo 
You're right and that is unfortunate. The fix is hanging in the draft PR https://github.com/corona-warn-app/cwa-website/pull/1267.

@dsarkar / @Ein-Tim 
If it is difficult to get agreement on the enhancements to https://www.coronawarn.app/en/faq/#error_log and https://www.coronawarn.app/de/faq/#error_log, then I suggest correcting the bad link fast and separately to the open PR #1267.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I prepared a PR for this because I thought exactly the same as you, it'll arrive in the next hour!

**Comment by Ein-Tim** [comment]
Please see #1273.

**Comment by ndegendogo** [comment]
Thanks for the fast fix 😁😁👍
