### ISSUE TITLE
FAQ - Revise articles about incompatibility warning card

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#1288]
## Where to find the issue
https://www.coronawarn.app/de/faq/#incompatibility_warning
https://www.coronawarn.app/en/faq/#incompatibility_warning

## Describe the issue

We agreed in https://github.com/corona-warn-app/cwa-website/pull/1211#discussion_r627438916 to split the article in two new articles to make it more user-friendly. The problem with the current article are:

* Partial and full incompatibility are mixed which can lead to the wrong assumption that the app doesn't work at all
* A lot of users wrongly assumed that the incompatibility was **caused** by release 2.2, while in fact it was only made visible by the new checks (see https://github.com/corona-warn-app/cwa-app-android/issues/3170)
* The wording/terminology used in the article turned out to be too technical in some places as we know from app store reviews (e.g. peripheral mode, BLE, bluetooth chip).

## Suggested change

Make two new FAQ articles for the changes introduced in 2.3: https://github.com/corona-warn-app/cwa-app-android/pull/3101

- `part_incompat` should explain partial incompatability
- `full_incompat` should explain full incompatibility

----

The version number was added by @MikeMcC399 in https://github.com/corona-warn-app/cwa-website/pull/1275

However, the sentence could be improved (https://github.com/corona-warn-app/cwa-website/pull/1275#discussion_r633271249). Maybe we should start the first sentence with this information:

"Since CWA release 2.2, the app will check if your device is fully capable to exchange random IDs..." 

----
We may need to drop most technical terms and focus more more on the outcome of incompatibility, e.g. instead of

> Because of it, the Corona-Warn-App cannot use Bluetooth Low Energy in its so-called “peripheral mode”.

we should use

> This means that your device is unable to **send** random IDs to other devices. However, you are still able to **receive** random IDs. Your own risk assesment is therefore not affected.

----
The term "incompatibility" can also be a bit problematic IMO, so we maybe have to choose a more "tame" term in the app and the FAQ. 

----
**Store reviews for context**

> Ich nutze die App von Anfang an und finde sie gut und sinnvoll. Besonders die Erweiterungen. Seit dem heutigen Update auf 2.2.1 leider eine Inkompatibilitätsmeldung. Angeblich kann mein Bluetooth keine Warnungen verschicken, sondern nur empfangen. Das ist natürlich nicht sinnvoll. Bisher hatte ich die Meldung nicht. Was ist da los? Ich habe keine Änderungen an den Einstellungen vorgenommen [...].

> Seit dem letzten Update v. 10.05. ist mein Bluetooth Chip plötzlich inkompatibel. Das kann ja wohl nicht sein. Mit der Vorgängerversion wieder alles okay. Geht das bei der Corona App jetzt genauso wie bei den meisten Banking Apps? Jedes Update eine Verschlimmbesserung?

> Nach dem Update vom 10/5 jetzt eine Inkompatibilität-swarnung weil Bluetooth Warnungen empfangen aber nicht senden kann.

> Ich habe Android 6 Eine App die 60.000.000€ in der Entwicklung gekostet hat zeigt nun an,das mein älteres Snartphone wofür es keine Updates mehr gibt inkompatibele Probleme hat. Eine App für diese Wichtigkeit sollte auf jeden Smartphone funktionieren egal wie alt Android auch ist. Da versagen staatliche Programmierer.

> Seit dem Update auf die Version 2.2.1 bekommen wir eine Inkompatibilitätsmeldung bei Bluetooth. Bis zu diese Version kamen keine Meldungen. Bitte korrigieren.

**Comment by heinezen** [comment]
@fynngodau I assume you would want to write or draft the articles? :)

In any case, we will try to further improve the articles with user feedback.

**Comment by MikeMcC399** [comment]
@heinezen 
Do we know what percentage of users will see the partial incompatible issue or the full incompatibility issue? My guess is that partial incompatibility is very low numbers and full incompatibility almost zero.

At the moment the app is released for minimum API 23 (Android 6 and above) and BLE has been available since Android 4.1. It is not possible to install on a device earlier than Android 6 (neither through the Google Play Store, nor by sideloading). The only report in GitHub so far since the release of 2.2.1 was about an Android 6 device which did not support peripheral mode.

Users who install the app from Google Play Store are prevented from installing on a device with no Bluetooth support or with no Bluetooth Low Energy support, because this is ruled out by the current manifest file.

If the article is spilt, you could try structuring them so that the introduction is less technical (like the text you proposed) then further down the article provide more technical details for those who would like to know. When I added the version number I looked for a quick, simple and non-contentious change, so certainly this can be optimized and better integrated.

**Comment by heinezen** [comment]
@MikeMcC399 We don't know the total number of users that are affected, but the numbers are indeed very low. However, they are not low enough to be insignificant because a few older but popular devices did not receive updates to support peripheral mode.

For the FP2, we know that peripheral mode was not supported with [Android 7 as the OS](https://forum.fairphone.com/t/corona-warn-app-von-fdroid-inkompatibel-auf-fp2/71072). They only recently fixed this with their Android 9 update. A Samsung device with Android 7 was also reported to have an incompatibility warning in the Play Store.

**Comment by fynngodau** [comment]
> I assume you would want to write or draft the articles? :)

Gladly so, but maybe only after my last Abiturprüfung before the holidays on Friday ;)

>  part_incomp should explain partial incompatability
>full_incomp should explain full incompatibility

In https://github.com/corona-warn-app/cwa-app-android/pull/3101 I actually linked to `part_incompat` and `full_incompat` because those are a bit more readable.

> We may need to drop most technical terms

> If the article is spilt, you could try structuring them so that the introduction is less technical (like the text you proposed) then further down the article provide more technical details for those who would like to know

I, too, would like to have an additional, more technical description them somewhere. Do you think it would be a good idea to create an additional article for users who want to know more, like this?: "What is the technical reason that my device is only partially compatible?"

> We don't know the total number of users that are affected, but the numbers are indeed very low.

Maybe this would be something that could be analyzed through the PPA system?

> The term "incompatibility" can also be a bit problematic IMO, so we maybe have to choose a more "tame" term in the app and the FAQ.

I think this is a good idea. Does anybody have any suggestion? We could also come up with a new icon that is less alert-y than the red warning triangle.

Another point here is that "Inkompatibilitätswarnung" is a very long term that needs to be line-wrapped, which doesn't look great.

> They only recently fixed this with their Android 9 update.

Thanks for the info, will add it to CCTG FAQ.

**Comment by fynngodau** [comment]
In the community slack, @vaubaehn shared a review by a user who was confused because the incompatibility warning was only sometimes showing. We should that this can happen when the status cannot be reliably detected.

**Comment by vaubaehn** [comment]
> In the community slack, @vaubaehn shared a review by a user who was confused because the incompatibility warning was only sometimes showing. We should that this can happen when the status cannot be reliably detected.

I hope that it is possible to find a good solution to prevent/to fix intermittent changes of the state. Hence, I propose to add something like "currently there are a few reports of users who experience intermittent changes of the state. We're looking into this and will fix this in an upcoming release" or similar...

**Comment by vaubaehn** [comment]
@fynngodau and still all the best for the final exams! :D

**Comment by fynngodau** [comment]
From looking at the code again, we reconstructed a more precise definition when this happens: if Android version < 8.0 and Bluetooth is turned off, detection doesn't work – then, no warning card is shown in any case.

**Comment by MikeMcC399** [comment]
@fynngodau 
It would be great to have an explanation of how the checks are done, just for a better understanding.

Also good luck from me for your Abi exams! ☘️ 🤞🏻

**Comment by dsarkar** [comment]
@fynngodau Fingers crossed!

**Comment by Ein-Tim** [comment]
Also from my side! Good luck!

**Comment by heinezen** [comment]
@fynngodau 

> In corona-warn-app/cwa-app-android#3101 I actually linked to part_incompat and full_incompat because those are a bit more readable.

Fixed it in my initial post

> I, too, would like to have an additional, more technical description them somewhere. Do you think it would be a good idea to create an additional article for users who want to know more, like this?: "What is the technical reason that my device is only partially compatible?"

We can maybe keep the information in the same entry, but only have the technical information at the end like @MikeMcC399 suggested. I don't see a problem with that as long as it is sectioned off properly and the entry doesn't get too long. However, if it does get *very* technical or there are too many details, a separate markdown file in https://github.com/corona-warn-app/cwa-documentation would be better. We can then link to this file.

> I think this is a good idea. Does anybody have any suggestion? We could also come up with a new icon that is less alert-y than the red warning triangle.

I though about something like *"eingeschränkte Sendefähigkeit/limited usage"*, but that is even longer and probably too vague :D Maybe it should be "XY not available" where XY is something that describes peripheral mode.

The alerty warning triangle could be replaced with an "info" exclamation mark.

Anyway, good luck for your exams :)

**Comment by heinezen** [comment]
@Ein-Tim @fynngodau @MikeMcC399 @vaubaehn @dsarkar 

I've added a few reviews from the store, so we can better judge where the problems with the current message are. Most of them are misinterpretations of the warning card.

**Comment by fynngodau** [comment]
I don't expect there to be too much technical information for our new entries. I agree that we should be able to fit them in the end like has been suggested.

> > Ich habe Android 6 Eine App die 60.000.000€ in der Entwicklung gekostet hat zeigt nun an,das mein älteres Snartphone wofür es keine Updates mehr gibt inkompatibele Probleme hat. Eine App für diese Wichtigkeit sollte auf jeden Smartphone funktionieren egal wie alt Android auch ist. Da versagen staatliche Programmierer.

It is sad to hear that people are judging the app based on such inaccurate assumptions.


> > […] Bis zu diese Version [sic] kamen keine Meldungen. Bitte korrigieren.

Can't exactly fix the older versions to also show the warning, can we? :(

> > Seit dem letzten Update v. 10.05. ist mein Bluetooth Chip plötzlich inkompatibel.

I think this one also includes a misunderstanding about whether the part with the full incompatibility applies to them. I'm glad we'll be able to fix this for the next version!

---

> Maybe it should be "XY not available" where XY is something that describes peripheral mode.

Sounds like a good idea. I'd have thought of the word "broadcasting" for this but it doesn't have a nice German translation and also doesn't fit too well…

> The alerty warning triangle could be replaced with an "info" exclamation mark.

I'm assuming you meant an "(i)" icon here?

I have opened a new Android issue to discuss these two items further: https://github.com/corona-warn-app/cwa-app-android/issues/3260

**Comment by MikeMcC399** [comment]
I think a blog article would be good, combined with a mention in the new features section of the next version of the Android app. It's unfortunate that this didn't happen with the 2.2 Android release, which might have prepared users for the added warning. Probably most users will have automatically updated by now, so there will not be many new occurrences of the error message. Even so, it would be good to put out a message and make the reasoning clear to affected users (in addition to any changes to the FAQ article.)

It would be great if the reaction from users was that they are grateful for the additional tests done by the app, and grateful for the additional information, instead of just being annoyed.

Perhaps we could have a description of the problem:
- why didn't the Google Play Store detect the missing BLE functionality and prevent installation or provide a warning?
- why didn't the app check in earlier releases?

How was this solved in the 2.2 Android app versions?

What is the recommended course of action for a user getting an incompatibility message?

I have some ideas about how the app could be made more appealing, and I will post these soon to https://github.com/corona-warn-app/cwa-app-android/issues/3260.

**Comment by fynngodau** [comment]
I opened #1291 to incorporate our ideas and am looking forward to your feedback.

**Comment by heinezen** [comment]
> It is sad to hear that people are judging the app based on such inaccurate assumptions.

Don't worry about it too much! With apps that have such a broad audience, communicating problems (as minor as they are) is always difficult because we have to keep the balance between information and reassurance. And sometimes, this doesn't work out because users bring in their own prejudices or misinterpretations. The best we can do is learn from it and improve :)

> > […] Bis zu diese Version [sic] kamen keine Meldungen. Bitte korrigieren.

> Can't exactly fix the older versions to also show the warning, can we? :(

I'm afraid backporting wouldn't help here. If the message were shown in the old versions, the complaints would probably be the same. From the user's POV, the previous versions had no problem because there was no visible feedback about it. They also act on impartial information which can lead to wrong conclusions. A similar thing also happened when we switched to ENFv2 and a lot of people thought that the app got worse at detecting risk encounters because they received less warnings, when it actually reduced the number of false positives.

> I'm assuming you meant an "(i)" icon here?

I've actually though of "(!)", but "(i)" is much better!

> Even so, it would be good to put out a message and make the reasoning clear to affected users (in addition to any changes to the FAQ article.)

We will answer the Play Store reviews directly with an explanation (maybe even before 2.3 releases).

**Comment by MikeMcC399** [comment]
I don't have an personal experience with a device which is incompatible, but I suspect that for most users of such devices that the only practical solution will be to update to a newer device. The devices which I have owned have always offered firmware updates automatically and I doubt if a device manufacturer will plan to update older firmware / device driver just because a user has contacted them.

The possibility that the only solution to the issue would be to update to a newer device is not mentioned, and I think it probably should be mentioned.

**Comment by fynngodau** [comment]
When adding the hint to update the firmware, I had the Fairphone 2 in mind, because there updating is actually a way to resolve the problem.

> I doubt if a device manufacturer will plan to update older firmware / device driver just because a user has contacted them.

I'm afraid that this is true. However, I am not in favor of adding the advice to buy a new device. It is, in most cases, not a practical solution. The (monetary and environmental) cost is at an imbalance with the benefit. For this reason, such an advice might upset users.

The should convey the advice: "Your app is working fine and your device is okay, but be aware of this limitation."

Of course depending on how this is formulated, adding the advice you proposed might make it sound more like: "It is not a good idea to use the app on this device. Better get a new one."

**Comment by MikeMcC399** [comment]
@fynngodau 

- For partial incompatibility getting a new device is probably not worth it.
- For full incompatibility a new device is probably the only option if a user wants to have exposure notification capabilities linked to BLE. For environmental or cost concerns, there is also the option of obtaining a device second-hand. In any case that should be the user's decision. I just wanted to avoid raising a reader's hopes too high that they could solve the problem for their existing device.

**Comment by heinezen** [comment]
@MikeMcC399 @fynngodau 

IMO recommending getting a new device wouldn't come across well because it is a very expensive solution. It will sound out of touch. Of course it depends how it's worded, but I would also not be in favour of putting it in.

**Comment by heinezen** [comment]
Fixed by https://github.com/corona-warn-app/cwa-website/pull/1291
