### ISSUE TITLE
[Discussion] GitHub links in FAQ entries - Bug Reporting Link

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-website#131]
## Feature description
The page should make clearer how bugs in the apps could be reported.

## Problem and motivation

Generic Github Links are ok, but for bugs, we could link directly to the app repos.

## Is this something you're interested in working on

Yes

**Comment by finnmglas** [comment]
Linking to the issuetrackers of the apps ([android][a-issues] / [ios][i-issues]) or directly linking to create a new issue ([android][a-new] / [ios][i-new]) may be appropriate here.

The `Get involved` section in the pages footer may be a good place to link to the most important repos (android, ios, docs, website):

![image](https://user-images.githubusercontent.com/40366035/87242002-097b4c00-c429-11ea-9598-4bf36357bdb4.png)


[a-issues]: https://github.com/corona-warn-app/cwa-app-android/issues
[i-issues]: https://github.com/corona-warn-app/cwa-app-ios/issues

[a-new]: https://github.com/corona-warn-app/cwa-app-android/issues/new/choose
[i-new]: https://github.com/corona-warn-app/cwa-app-ios/issues/new/choose

**Comment by dsarkar** [comment]
Dear community,

It is true that very few FAQ entries on the website have a direct link to GitHub issues or to the repositories. Following suggestions:

- We keep this issue open in order to discuss in general where to update FAQ with links to GitHub
- In future we include more GitHub links in new or updated FAQ entries, where it makes sense. For example, in this FAQ entry https://www.coronawarn.app/en/faq/#ExposureDetectionIsAlreadyRunning there are three  links.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @tkowark, I think we can close this one. We are trying to do as suggest, where applicable. Best, DS
