### ISSUE TITLE
Suggest to take PCR test in `red_card_how_to_test`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1318]
## Enhancement description
https://www.coronawarn.app/en/faq/#red_card_how_to_test should link to https://www.coronawarn.app/de/faq/#rat_red_card_which_test to suggest that after a high risk warning from CWA, a PCR test should be taken and not a RAT. 
Alternative, https://www.coronawarn.app/en/faq/#red_card_how_to_test can directly mention this. 

## Problem and motivation
See https://github.com/corona-warn-app/cwa-wishlist/issues/536

## Is this something you're interested in working on
Yes, after it has been clarified wether we link to the other entry or mention it directly.

**Comment by dsarkar** [comment]
@Ein-Tim @di-sc Thanks. https://www.coronawarn.app/en/faq/#red_card_how_to_test  will be updated. Just had another thought. It should also mention recommendations for other cases: What to do if warned person is: a) vaccinated, b) recovered from COVID-19

**Comment by Ein-Tim** [comment]
@dsarkar 

Okay! Will you take this over? 
If not (now) I could provide a PR which links from https://www.coronawarn.app/en/faq/#red_card_how_to_test to https://www.coronawarn.app/de/faq/#rat_red_card_which_test.

**Comment by MikeMcC399** [comment]
@dsarkar 

> Just had another thought. It should also mention recommendations for other cases: What to do if warned person is: a) vaccinated, b) recovered from COVID-19

This is also mentioned in https://github.com/corona-warn-app/cwa-wishlist/issues/457 (https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6545).

**Comment by di-sc** [comment]
@dsarkar 
> Just had another thought. It should also mention recommendations for other cases: What to do if warned person is: a) vaccinated, b) recovered from COVID-19
> 
> Or a link to a site, where clear recommendations are given.

Good idea but I think currently it is diffucult to give a clear recommendation as also discussed in [#457](https://github.com/corona-warn-app/cwa-wishlist/issues/457) even not by the RKI. Additionally the behavior would be dependent on how long ago the vaccination or recovery was. (By the way the app could also give a hint for refreshing the vaccination - later on). I would rather suggest to hide such complex decisions from the user, enable them to add their vaccination or recovery status (with date) to the app, and put it into the risk calculation algorithm as suggested in [#488](https://github.com/corona-warn-app/cwa-wishlist/issues/488).

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I went through all the FAQs to address the issue https://github.com/corona-warn-app/cwa-website/issues/1238 "FAQ: Differentiate between PCR Test and Rapid Antigen Test". I hoped originally that the Open Source Team would pick up this issue, but after three months waiting I thought it was worth putting forward individual PRs, which by now have all been merged.

I missed this issue (https://github.com/corona-warn-app/cwa-website/issues/1318) when I submitted https://github.com/corona-warn-app/cwa-website/pull/1604. Sorry for that!

https://www.coronawarn.app/en/faq/#red_card_how_to_test now links to https://www.coronawarn.app/en/faq/#rat_red_card_which_test 

and 

https://www.coronawarn.app/de/faq/#red_card_how_to_test now links to https://www.coronawarn.app/de/faq/#rat_red_card_which_test 

Both articles mention PCR tests directly in the text, in addition to the links.

So the original aims of this issue (https://github.com/corona-warn-app/cwa-website/issues/1318) are resolved through PR https://github.com/corona-warn-app/cwa-website/pull/1604.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for your efforts! I agree with you, this issue has been resolved and therefore I'll close it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Some other comments for you, @dsarkar and @di-sc:

> What to do if warned person is: a) vaccinated, b) recovered from COVID-19

https://www.coronawarn.app/en/faq/#red_card_how_to_test "Red Card? How to go through Corona testing" also links to
[How to behave if I am partially or completely vaccinated, but receive a red warning in the Corona-Warn-App?](https://www.coronawarn.app/en/faq/#vac_cert_red_warning) due to PR #1604.

There are no specific recommendations for a person who receives a red warning and who has recovered from COVID-19. Unless the RKI makes some recommendation for this case, then the general recommendation would apply i.e. "If the Corona-Warn-App indicates a high infection risk with the red card, please isolate yourself quickly and consult a doctor to get a PCR test if necessary." If this point needs to be tracked, it would be better to open a new issue on the special topic, otherwise it will get lost.

Wishlist https://github.com/corona-warn-app/cwa-wishlist/issues/457 "Advice for app use by people who have been vaccinated" is closed as resolved.

Wistlist https://github.com/corona-warn-app/cwa-wishlist/issues/536 "Add PCR test recommendation after red warning notification" from @di-sc is still open. I will make a comment there.
