### ISSUE TITLE
Update FAQ https://www.coronawarn.app/en/faq/#backup

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1319]
## Where to find the issue

https://www.coronawarn.app/en/faq/#backup
https://github.com/corona-warn-app/cwa-website/pull/1313#discussion_r642071352

## Describe the issue

- include more general information about backup.

## Suggested change

- add info that vaccination certificate is not in the backup

---
[EXPOSUREAPP-14339](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14339)

**Comment by fynngodau** [comment]
Further reference, so that you don't have to click through the whole PR with all its feedback: https://github.com/corona-warn-app/cwa-website/issues/1311#issuecomment-850884993

>* >  Ist das Impfzertifikat in meinem Backup enthalten?
>
>   This question is not directly answered in the block that follows it. One option would be to remove it here and integrate it with the `backup` FAQ.
>   Then, the [`backup`](https://www.coronawarn.app/en/faq/#backup) FAQ should be updated to reflect this information, and to also address the other features of the app (contact journal etc.). It should also explain that this is done to ensure that the sensitive data that the Corona-Warn-App stores doesn't leave the device.

**Comment by Ein-Tim** [comment]
@dsarkar Is there any progress about this? See also #1766. I'd offer a PR as described in the OP of #1766.

**Comment by MikeMcC399** [comment]
This is also related to the enhancement request https://github.com/corona-warn-app/cwa-wishlist/issues/407 which says that the reset app function should give the user more information about what data is lost through resetting the app before they attempt the reset.

Since no data is saved by automatic backup, these two topics are related.

**Comment by Ein-Tim** [comment]
🙋🏻‍♂️ I'll start working on this in the next days.

**Comment by Ein-Tim** [comment]
Suggestion: Bundle all backup related FAQ entries in one entry, so remove the FAQ entry `new_device` and put all information in `backup`.

Does this sound good to you @dsarkar?

**Comment by MikeMcC399** [comment]
Please keep two separate topics or even add a third topic concerning general considerations for backup on an existing device, for instance if a user needs to do a factory reset on one device.

- https://www.coronawarn.app/en/faq/results/#backup "Will the collected random IDs be included when I backup data on my phone?"
- https://www.coronawarn.app/en/faq/results/#new_device "What do I have to consider when switching to a new device?"

The scenarios of moving to a new device and staying on an existing device are different and should be kept separate.

**Comment by Ein-Tim** [comment]
So a new article for the suggested steps before switching phones or restoring from a backup? 

Isn't this a bit confusing, the articles already now spread through different categories, so adding another one will make it even harder for the user to find the information they are looking for. 

I, as a user, would expect that if I enter the search term "Backup", I'm presented with bundled information
a) whether data of the app is included in a backup
b) what I have to consider before switching phones / restoring from a backup

Do you disagree here?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for bringing up the search topic in relation to "backup". It made me realize that there are several articles which touch on this subject. This seems like a complex area and of course, not only have the FAQs have been restructured since this issue was opened almost one year ago,  but there has been a lot of additional functionality added to the app!

Section | Topic | Anchor | Title
--- | --- | --- | ---
App Features | Certificates | [#eu_dcc_export](https://www.coronawarn.app/en/faq/results/#eu_dcc_export) | How do I create a printout of my EU Digital COVID Certificate?
App Features | Certificates | [#vac_cert_multiple_scan_possible](https://www.coronawarn.app/en/faq/results/#vac_cert_multiple_scan_possible) | Will vaccination certificates be included in my backup?
Troubleshooting | Common issues | [#new_device](https://www.coronawarn.app/en/faq/results/#new_device) | What do I have to consider when switching to a new device?
Troubleshooting | Resolved | [#migration_Apple](https://www.coronawarn.app/en/faq/results/#migration_Apple) | [Apple/iOS]: Migrating to new phone and backup and restore - app does not work
Technical Context | Risk Assessment | [#backup](https://www.coronawarn.app/en/faq/results/#backup) | Will the collected random IDs be included when I backup data on my phone?
Glossary | Backup |  [#glossary_backup](https://www.coronawarn.app/en/faq/results/#glossary_backup) | Backup

Probably it's not a good idea to re-purpose the #backup article, which covers just one very specific topic, and make it more general. I suggest though to wait until @dsarkar is available again (perhaps after the Easter weekend) and check his latest thoughts and suggestions.

**Comment by Ein-Tim** [comment]
Sounds good @MikeMcC399!

Enjoy your Friday & the easter week-end!

**Comment by molarya1** [comment]
Hi @MikeMcC399 @dsarkar just wanted to give a heads up that I am working alongside @Ein-Tim on this issue. Hope everyone had a great Easter weekend and looking forward to hearing back to get the ball rolling here! :)

**Comment by Ein-Tim** [comment]
Hey @dsarkar! 

Were you able to get this clarified? What should be done here? Please let us know what you suggest. Thanks!

**Comment by Ein-Tim** [comment]
@dsarkar Please, could you come back to this issue if you want me and @molarya1 to work on it. If we don't get any feedback how to proceed, we can't start working on this. If you don't want the community to work on this, just let us know.

**Comment by Ein-Tim** [comment]
@dsarkar 

We didn't hear back from you for more than a month. Could you please come back to this item.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 @molarya1  Will come back to you! Thanks for your patience!

**Comment by Ein-Tim** [comment]
@dsarkar Version 2.24 has been release, so I though you might have time to come back to us on this issue? :)

**Comment by larswmh** [comment]
We're very sorry that this issue has been stale for so long, and would now like to finally get this done. Are you still interested in working on this @Ein-Tim? We think that the idea with bundling the related articles into a seperate section would be a good idea. "Troubleshooting" would be the most fitting topic for this in our opinion. It would be good to work with article duplicates like in the "Background updates" section, so that the original article stays in the same place.

**Comment by Ein-Tim** [comment]
@larswmh 

Sorry, but I'm quite busy atm, so it would be great if you could do that!

**Comment by MikeMcC399** [comment]
- PR #3257 adds the list from https://github.com/corona-warn-app/cwa-website/issues/1319#issuecomment-1100130651 to a separate FAQ list

**Comment by MikeMcC399** [comment]
- PR #3257 was closed and replaced by PR #3260 to resolve this issue
