### ISSUE TITLE
FAQ does not mention Luca QR codes

### ISSUE THREAD

**Issue by 2019-05-10** [corona-warn-app/cwa-website#1461]
According to several sources CWA is supposed to be able to read Luca QR codes by now.
(Obviously, that's still not the case, yet the feature is of great interest not only to me)
None of these sources seems to be the CWA web site -- suspicioulsly, the FAQ does not even mention Luca, let alone contains information about the status.

Please, add (und update) information about that to the FAQ, even if it is just "WIP" or "not going to happen".

**Comment by Ein-Tim** [comment]
I'd like to create a FAQ entry for this, since I think it could be hard to get a quick approval if mentioning luca, I'd just write that the CWA event-registration feature is currently only compatible with QR-Codes that were created within the CWA or via https://www.coronawarn.app/de/eventregistration/. 

I'll open a PR for this in the next days, if there's nothing that speaks against it from your side (@dsarkar & @MikeMcC399)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I'd just write that the CWA event-registration feature is currently only compatible with QR-Codes that were created within the CWA or via https://www.coronawarn.app/de/eventregistration/.

I don't know if that statement is true. It would be good to get an official response to https://github.com/corona-warn-app/cwa-website/issues/1189. Is the list of allowlisted Event Registration apps empty or not? If it is not empty, what apps are allowlisted?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I agree. Looking at the code (https://github.com/corona-warn-app/cwa-server/blob/deeaeb4bb3c95b1388349fa2e2499f6989811103/services/distribution/src/main/resources/main-config/v2/presence-tracing-parameters.yaml#L112), to me, it seems like only CWA-own QR-Codes are allowlisted.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I suggest adding to the list of questions in:

https://www.coronawarn.app/en/faq/#check_in_qr_code

**Can Event QR codes from third-party apps be used?**

- Not at this time.

or, if applicable
- Yes. The following apps provide compatible QR codes: xx, yy, zz.

**Comment by MikeMcC399** [comment]
There is another new issue report in https://github.com/corona-warn-app/cwa-documentation/issues/658, so it would definitely be good to have an approved and published FAQ answer regarding the status of support of Luca QR event registration QR codes by CWA.

**Comment by Ein-Tim** [comment]
I opened #1482 to get this information in the FAQ, recently there are many users on Twitter asking the same question, so it definitely makes sense to add this in the near future. Fell free to comment in #1482.

**Comment by Ein-Tim** [comment]
@2019-05-10 The change from #1482 is now live, here's a screenshot: 
![DE](https://user-images.githubusercontent.com/67682506/125782924-5317d8e9-c96a-404d-a93b-073670e5e1bf.jpg)


Do you consider this as implemented and would you close this issue?

**Comment by 2019-05-10** [comment]
I strongly recommend to put the term "Luca" in somewhere.
That's by far the most used/best known of those apps, and I assume most people rather search for that term than parsing the ToC to locate that information. 
If I didn't know what to look for I may have overlooked that section ...

How to ensure that section is updated if anything changes?

**Comment by Ein-Tim** [comment]
@2019-05-10 

> I strongly recommend to put the term "Luca" in somewhere.
That's by far the most used/best known of those apps, and I assume most people rather search for that term than parsing the ToC to locate that information.
If I didn't know what to look for I may have overlooked that section ...

I understand your concern and I'll open a PR for this, but it could be that this takes some time because I'm quite sure that for this there needs to be an internal review. Thanks for your feedback.

> How to ensure that section is updated if anything changes?

As you can see in the PR section of this repository, the website, especially the FAQ section, is updated nearly daily, with new information, fixes ans more. 
As soon as there are any new on the topic (communicated through https://github.com/corona-warn-app/cwa-server/pull/1362, https://github.com/corona-warn-app/cwa-documentation/issues/590 or https://github.com/corona-warn-app/cwa-wishlist/issues/530), we will update this entry.

**Comment by Ein-Tim** [comment]
PR #1500 opened, which proposes to add a mention of the "luca" app to the FAQ.

**Comment by Ein-Tim** [comment]
As promised @2019-05-10, here's the latests information reg. "luca" and CWA:

https://github.com/corona-warn-app/cwa-server/pull/1362#issuecomment-882052293 says:

> The feature has a good progress. We hope we can finish the feature soon.

**Comment by Ein-Tim** [comment]
@2019-05-10 

Next update: Seems like the CWA will be able to scan luca QR codes from version 2.13 on. 

See https://github.com/corona-warn-app/cwa-server/pull/1594

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-website/pull/2041

**Comment by dsarkar** [comment]
https://www.coronawarn.app/de/faq/#check_in_luca

**Comment by Ein-Tim** [comment]
Let‘s close this issue @2019-05-10, or?
