### ISSUE TITLE
Create FAQ entry: vac_cert_booster 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1649]
## Feature description

- Create FAQ entries:
**EN** https://www.coronawarn.app/en/faq/#vac_cert_booster 
**DE** https://www.coronawarn.app/de/faq/#vac_cert_booster

## Problem and motivation

- New feature booster vaccination
  - if a booster notification rule applies to the DCCs of the person, the rule description and a link to the FAQ is shown
Link to FAQ:
**EN** https://www.coronawarn.app/en/faq/#vac_cert_booster 
**DE** https://www.coronawarn.app/de/faq/#vac_cert_booster

Related:
Internal Tracking ID: [EXPOSUREAPP-8718](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8718)
Internal Tracking ID: [EXPOSUREAPP-9068](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9068)

**Comment by Ein-Tim** [comment]
@dsarkar 

Maybe it makes sense to create a FAQ entry for this already now, so that users who have the question what the current status about booster vaccination certificates is can find an answer?

**Comment by dsarkar** [comment]
@Ein-Tim Sure, sounds good to me.

**Comment by loki-cui** [comment]
**Wie erfahre ich von Auffrischungsimpfungen im Kontext von Corona?**  

Durch die Gesundheitsminister-Konferenz wurde inzwischen die Regelung zu Covid-19-Auffrischimpfungen beschlossen. Eine zusätzliche Auffrischimpfung soll helfen, die neutralisierenden Antikörpertiter wieder zu erhöhen, die nach der Grundimmunisierung mit der Zeit absinken können. Das gilt insbesondere bei den Personengruppen, bei denen nach einer Grundimmunisierung eine gedämpfte Impfantwort vermutet oder erkannt wird.
Die Corona-Warn-App wird darauf hinweisen, eine Auffrischimpfung in Betracht zu ziehen, falls bestimmte Bedingungen erfüllt sind. Diese Bedingungen basieren auf den Empfehlungen der Paul-Ehrlich-Instituts sowie der Ständigen Impfkommission (STIKO) des Robert Koch-Instituts (RKI). 

[ Hier evtl. einen Screenshot, wie so eine Warnung aussieht. ]

Wie lange jemand durch eine Covid-19-Impfung (Grundimmunisierung) tatsächlich geschützt ist, hängt von verschiedenen Faktoren ab und lässt sich daher nach heutigem Kenntnisstand nicht pauschal beantworten. Deswegen werden die  entsprechenden Regeln für Impfschemata und Auffrischimpfungen in der Corona-Warn-App in Abstimmung mit dem RKI entsprechend den Entwicklungen und neuen Erkenntnissen fortlaufend überprüft und angepasst.

**Wie verwalte ich Auffrischungsimpfungen in der CWA?**

In einem der kommenden Releases unterstützt die Corona-Warn-App auch den Import von Zertifikaten, die eine Auffrischimpfung dokumentieren. 
Die Anwender erhalten dazu einen Hinweis, ggf. eine Auffrischimpfung in Betracht zu ziehen. Der Hinweis basiert auf nationalen Regeln, die in Absprache mit dem Robert Koch-Institut (RKI) implementiert wurden. Diese Regeln werden fortlaufend geprüft und entsprechend den Entwicklungen und neuen Erkenntnissen angepasst.

Bitte beachten Sie: 
Das Zertifikat zur Auffrischungsimpfung ist nur gültig, wenn Sie auch die nötige Grundimmunisierung durch das entsprechende letzte Zertifikat der Impfreihe nachweisen können. Löschen Sie bitte die anderen Impfzertifikate **nicht** aus der CWA! Da bisher noch keine einheitlichen EU-Standards zu diesem Thema festgelegt wurden, sollte man insbesondere bei Reisen ins Ausland auch die Zertifikate der Grundimmunisierung mit sich führen, sei es in der CWA, als PDF, oder als Papierausdruck. Wir empfehlen daher alle Impfzertifikate in der App zu behalten, auch wenn diese nicht mehr aktuell sind.


**How do I become aware of booster vaccinations in the context of Corona?**

The Conference of Health Ministers has now passed a regulation on Covid 19 booster vaccinations. An additional booster vaccination is designed to help raise neutralizing antibody titers again, which may decline over time after basic immunization. This becomes particularly important if a weak/muted vaccine response is assumed or recognized after basic immunization in certain groups of vulnerable people.
The Corona Warn App (CWA) will notify the user to consider a booster vaccination if certain conditions are met. These conditions are based on the recommendations of the Paul Ehrlich Institute and the Permanent Vaccination Commission (STIKO) of the Robert Koch Institute (RKI).

[ Here in EN a sample how the notification will look like. ]

How long someone is effectively protected by a Covid 19 vaccination (basic immunization) depends on several factors and can therefore not be answered in general terms according to current knowledge. For this reason, the corresponding CWA rules for vaccination schedules and booster vaccinations are continuously reviewed and adapted in coordination with the RKI according to developments and new findings.



**How do I manage booster vaccination certificates in my CWA?**

In one of the upcoming releases, the Corona warning app allows importing certificates documenting a booster vaccination. 
Users will receive a notification to consider a booster vaccination if necessary. The notification is based on national rules that have been implemented in collaboration and alignment with the Robert Koch Institute (RKI). These rules are continuously reviewed and adapted according to developments and new findings.

Please note: 
The booster vaccination certificate is only valid if you can also prove the required basic immunization by the corresponding last certificate of the vaccination series. Please do **not** delete the other vaccination certificates from the CWA!  Since no uniform EU-standards have yet been defined on this topic, you should also carry the basic immunization certificates with you, especially when traveling abroad, whether in the CWA, as a PDF, or as a paper printout. We therefore recommend keeping all vaccination certificates in the app, even if they are no longer up to date.

**Comment by MikeMcC399** [comment]
@loki-cui 
Good texts!
I suggest to write COVID capitalized, like in other FAQ entries and in RKI page
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html.
