### ISSUE TITLE
`package-lock.json` is missing some `resolved` and `integrity` values

### ISSUE THREAD

**Issue by Marcono1234** [corona-warn-app/cwa-website#1662]
## Your Question
There are two cases in the `package-lock.json` where the `resolved` and `integrity` values are missing:
https://github.com/corona-warn-app/cwa-website/blob/4142215c9b3b742480ba5f3446cbedd7843d7833/package-lock.json#L4372
https://github.com/corona-warn-app/cwa-website/blob/4142215c9b3b742480ba5f3446cbedd7843d7833/package-lock.json#L13274

It appears #1499 made this change, but I could not find any explanation for this. Is there a reason why this was done?
When I run `npm install` it fills these missing values, but the build succeeds without any (noticable) issues.

**Comment by MikeMcC399** [comment]
@Marcono1234 

It seems that
`npm audit fix`
can cause this change.

I've tended to use
`npm ci`
on a clone of the repository instead of
`npm install`

and then if there are any issues with `package.json` I've requested the Open Source Team in the past to update and test, so that we're are synced.

Do you think that the differences you noticed will have any negative effect? I'm using npm 6.14.13. What about you?

https://github.com/corona-warn-app/cwa-website/pull/1499 came from @chrisenitan and it was merged by @svengabr. 
In that PR `"cypress": "^4.12.1"` changed to `"cypress": "^7.6.0"` and I imagine that any other changes to `package-lock.json` would have been incidental and unintended.

**Comment by Marcono1234** [comment]
> Do you think that the differences you noticed will have any negative effect?

I am not completely sure if `resolved` is actually still used, see [this StackOverflow answer](https://stackoverflow.com/a/53827243).
I assume `integrity` might help with detecting corrupted downloads and maybe also prevent attackers from forging packages, though this is rather unlikely since it would require them to perform a MITM attack on a HTTPS connection or take over the npm registry.
Note though that I am not very familiar with npm.

> I'm using npm 6.14.13. What about you?

I am using 6.14.8.

**Comment by Marcono1234** [comment]
Thanks for the clarification, I will close this issue then.
