### ISSUE TITLE
Release 2.9: Screenshots, FAQ, Privacy documents, update gulpfile, blog

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#1674]
Internal Tracking ID: [EXPOSUREAPP-9101](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9101)

- [x] Gulpfile: Only update shortly before release roll out, in order to avoid merge conflicts
- [x] Update Privacy Notice Files 
https://github.com/corona-warn-app/cwa-website/pull/1687
Internal Tracking ID: [EXPOSUREAPP-9237](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9237)
- [ ] Publish blog 
Internal Tracking ID: [EXPOSUREAPP-9125](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9125) 
Internal Tracking ID: [EXPOSUREAPP-9126](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9126) 
- [x] FAQs Internal Tracking ID: [EXPOSUREAPP-9107](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9107) 
  - [x] "In Vertretung warnen" 
https://github.com/corona-warn-app/cwa-website/issues/1695
https://github.com/corona-warn-app/cwa-website/pull/1712
  Internal Tracking ID: [EXPOSUREAPP-9181](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9181) 
  - [x] update FAQ regarding recovered persons. 
  https://github.com/corona-warn-app/cwa-website/issues/1713
  Internal Tracking ID: [EXPOSUREAPP-9182](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9182)
  - [x] FAQs regarding booster vaccination
https://github.com/corona-warn-app/cwa-website/pull/1712
https://github.com/corona-warn-app/cwa-website/issues/1649
- [x] Screenshots 
https://github.com/corona-warn-app/cwa-website/pull/1707
Internal Tracking ID: [EXPOSUREAPP-8856](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8856)
 

Screenshots in the assets:
- https://github.com/corona-warn-app/cwa-app-ios/releases
- https://github.com/corona-warn-app/cwa-app-android/releases

Content to include:
- In Vertretung warnen: Als Organisator eines Events können Sie nun nach Aufforderung durch das Gesundheitsamt Ihre Gäste in Vertretung für eine positiv getestete Person warnen, die am Event teilgenommen hat, aber nicht über die Corona-Warn-App eingecheckt war.
- Sofortige Impfstatusanzeige für Genesene: Für Genesene wird ab jetzt direkt nach der ersten Impfung der vollständige Impfschutz in der Corona-Warn-App angezeigt. Die zweiwöchige Wartezeit entfällt bei allen Impfstoffen außer bei Johnson & Johnson.
- new section: "In Vertretung warnen"
  - anchor suggestions (and ios_xzy): 
    - android_event_organizer_warning
    - android_representative_warning
    - android_warn_on_behalf_of
- Files - "In Vertretung warnen"
  - TraceLocationWarnInfoFragment.png - wrong file name: Internal Tracking ID: [EXPOSUREAPP-9209](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9209)
  - TestCertificateDetailsFragment.png
  - TraceLocationSelectionFragment.png
  - TraceLocationWarnDurationFragment.png
  - TraceLocationWarnTanFragment.png
  - TraceLocationOrganizerThanksFragment.png

<img width="940" alt="131128071-08a4d8ef-16bd-4051-98ec-34e3df6e6808" src="https://user-images.githubusercontent.com/67682506/131196023-f2e90981-cbe4-40a1-8803-42c9a0f4dad7.png">

**Comment by dsarkar** [comment]
@Ein-Tim Yes indeed, thanks.

**Comment by Ein-Tim** [comment]
One more question:
Why do Johnson & Johnson vaccinated people who recovered from COVID still have to wait 14 days? What's the legal basis for this?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Why do Johnson & Johnson vaccinated people who recovered from COVID still have to wait 14 days? What's the legal basis for this?

The RKI FAQ
[COVID-19 und Impfen: Antworten auf häufig gestellte Fragen (FAQ) Gesamtstand: 27.8.2021](https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/gesamt.html) answers the question:
**"Wer gilt laut rechtlichen Verordnungen als vollständig geimpft bzw. genesen?"**

That FAQ does not include the exception below regarding J & J.

> Sofortige Impfstatusanzeige für Genesene: Für Genesene wird ab jetzt direkt nach der ersten Impfung der vollständige Impfschutz in der Corona-Warn-App angezeigt. Die zweiwöchige Wartezeit entfällt bei allen Impfstoffen außer bei Johnson & Johnson.

It may be just a practical problem. Johnson & Johnson is a 1/1 vaccination, so anybody who received that without previously being recovered will have to wait 14 days. But how do you distinguish a Johnson & Johnson 1/1 vaccination certificate issued for a person who was **not** previously infected compared to a certificate issued for a person who **was** infected?

In the case of vaccinations which are normally only complete with 2/2, the inference of a 1/1 for instance with AstraZeneca is that it must be for a recovered person.

Maybe  @vaubaehn could cross-check that since he is much more familiar with the status and developments of the DCC schema on https://github.com/ehn-dcc-development/ehn-dcc-schema?

**Comment by Ein-Tim** [comment]
> It may be just a practical problem. Johnson & Johnson is a 1/1 vaccination, so anybody who received that without previously being recovered will have to wait 14 days. But how do you distinguish a Johnson & Johnson 1/1 vaccination certificate issued for a person who was not previously infected compared to a certificate issued for a person who was infected?

> In the case of vaccinations which are normally only complete with 2/2, the inference of a 1/1 for instance with AstraZeneca is that it must be for a recovered person.

Yes, this must be the answer to my question. There is no way to differentiate between normally vaccinated people with 1/1 or recovered people with 1/1. Thanks Mike!

**Comment by vaubaehn** [comment]
Hi @MikeMcC399 and @Ein-Tim ,
sorry for the late response - I somehow lost your ping, and @dsarkar 's closing of this issue was the wake-up call.

> > Why do Johnson & Johnson vaccinated people who recovered from COVID still have to wait 14 days? What's the legal basis for this?
> 
> The RKI FAQ
> [COVID-19 und Impfen: Antworten auf häufig gestellte Fragen (FAQ) Gesamtstand: 27.8.2021](https://www.rki.de/SharedDocs/FAQ/COVID-Impfen/gesamt.html) answers the question:
> **"Wer gilt laut rechtlichen Verordnungen als vollständig geimpft bzw. genesen?"**
> 
> That FAQ does not include the exception below regarding J & J.

> It may be just a practical problem. Johnson & Johnson is a 1/1 vaccination, so anybody who received that without previously being recovered will have to wait 14 days. But how do you distinguish a Johnson & Johnson 1/1 vaccination certificate issued for a person who was **not** previously infected compared to a certificate issued for a person who **was** infected?
> 
> In the case of vaccinations which are normally only complete with 2/2, the inference of a 1/1 for instance with AstraZeneca is that it must be for a recovered person.

> Maybe @vaubaehn could cross-check that since he is much more familiar with the status and developments of the DCC schema on https://github.com/ehn-dcc-development/ehn-dcc-schema?

Actually, the idea to solve the technical problem to distinguish vaccinations from non-infected persons and recovered persons by just looking to/reading out the vaccination certificate and to rely on the total series of doses, is great imho. But I think, we would run into a legal problem then: it would be discrimination of people who received Johnson&Johnson after recovery just for technical means.
Indeed, it's not possible to conclude about the recovery status, when solely looking to the vaccination certificate due to restrictions in the current eHN DCC schema ("only one event allowed" per DCC). You would need the combination of both certificates, vaccination and recovery, to evaluate the effective validity of immunization status.
However, CWA will check the booster validity also for recovered persons from v2.10 on (see https://github.com/corona-warn-app/cwa-app-android/pull/4001): CWA will assemble a kind of artificial DCC and submit it to the CertLogic engine, and the engine will be fed with special crafted "booster rules", that will only be available in/for Germany for now. By this, the separation of certificates can be circumvented. Unfortunately, the design of the eHN DCC will not support business rules validation in a similar way currently. To make it possible, _all_ wallet apps in EU and elsewhere would need to be adapted to use a similar approach like CWA will do. For verifier apps it would even get more complicated, as they would need to scan 2 QR codes serially, but _just in some cases_, which would mean more effort for gate keeper and user during the control.

This is why I think, that the exception for Johnson&Johnson has other reasons. Probably there is not enough scientific evidence yet (finished studies) that Johnson&Johnson is able to protect recovered persons after one single shot in a similar degree (immediately) like the other vaccines. I made a fast search on secondary sources, but couldn't find anything useful in this subject. I didn't look into primary sources so far.

By the way, EU countries handle Johnson and Johnson differently, too, when validating business rules:

<details><summary>Netherlands wants 28 days until vaccination is valid</summary>

```json
[
   {
      "Type":"Acceptance",
      "SchemaVersion":"1.0.0",
      "Engine":"CERTLOGIC",
      "EngineVersion":"0.7.5",
      "CertificateType":"Vaccination",
      "Description":[
         {
            "lang":"en",
            "desc":"A vaccination with the Janssen vaccine has to be administered at least 28 days ago."
         },
         {
            "lang":"nl",
            "desc":"Een vaccinatie met het Janssen-vaccin moet ten minste 28 dagen geleden uitgevoerd zijn."
         }
      ],
      "ValidFrom":"2021-08-14T00:00:00+02:00",
      "ValidTo":"2030-06-01T00:00:00Z",
      "AffectedFields":[
         "v.0.dt",
         "v.0.mp"
      ],
      "Logic":{
         "if":[
            {
               "===":[
                  {
                     "var":"payload.v.0.mp"
                  },
                  "EU/1/20/1525"
               ]
            },
            {
               "if":[
                  {
                     "before":[
                        {
                           "plusTime":[
                              {
                                 "var":"payload.v.0.dt"
                              },
                              -1,
                              "day"
                           ]
                        },
                        {
                           "plusTime":[
                              "2021-08-14",
                              -1,
                              "day"
                           ]
                        }
                     ]
                  },
                  {
                     "not-before":[
                        {
                           "plusTime":[
                              {
                                 "var":"external.validationClock"
                              },
                              -1,
                              "day"
                           ]
                        },
                        {
                           "plusTime":[
                              {
                                 "var":"payload.v.0.dt"
                              },
                              14,
                              "day"
                           ]
                        }
                     ]
                  },
                  {
                     "not-before":[
                        {
                           "plusTime":[
                              {
                                 "var":"external.validationClock"
                              },
                              -1,
                              "day"
                           ]
                        },
                        {
                           "plusTime":[
                              {
                                 "var":"payload.v.0.dt"
                              },
                              28,
                              "day"
                           ]
                        }
                     ]
                  }
               ]
            },
            true
         ]
      },
      "Identifier":"VR-NL-0006",
      "Version":"1.0.0",
      "Country":"NL"
   }
]
```

</details>

<details><summary>and Ukraine wants 15 days until vaccination is valid</summary>

```json
[
   {
      "Type":"Acceptance",
      "SchemaVersion":"1.0.0",
      "Engine":"CERTLOGIC",
      "EngineVersion":"0.7.5",
      "CertificateType":"Vaccination",
      "Description":[
         {
            "lang":"en",
            "desc":"When the vaccine COVID-19 Vaccine Janssen, the certificate is not valid until 15 days from the date of vaccination."
         },
         {
            "lang":"ua",
            "desc":"\u041a\u043e\u043b\u0438 \u0432\u0430\u043a\u0446\u0438\u043d\u0430 COVID-19 Vaccine Janssen, \u0442\u043e \u0441\u0435\u0440\u0442\u0438\u0444\u0456\u043a\u0430\u0442 \u043d\u0435 \u0434\u0456\u0439\u0441\u043d\u0438\u0439 \u0434\u043e 15 \u0434\u043d\u044f \u0432\u0456\u0434 \u0434\u0430\u0442\u0438 \u0449\u0435\u043f\u043b\u0435\u043d\u043d\u044f."
         }
      ],
      "ValidFrom":"2021-08-22T10:00:00Z",
      "ValidTo":"2030-06-01T00:00:00Z",
      "AffectedFields":[
         "v.0",
         "v.0.mp",
         "v.0.dt"
      ],
      "Logic":{
         "if":[
            {
               "var":"payload.v.0"
            },
            {
               "if":[
                  {
                     "===":[
                        {
                           "var":"payload.v.0.mp"
                        },
                        "EU/1/20/1525"
                     ]
                  },
                  {
                     "not-after":[
                        {
                           "plusTime":[
                              {
                                 "var":"payload.v.0.dt"
                              },
                              15,
                              "day"
                           ]
                        },
                        {
                           "plusTime":[
                              {
                                 "var":"external.validationClock"
                              },
                              -1,
                              "day"
                           ]
                        },
                        {
                           "plusTime":[
                              {
                                 "var":"payload.v.0.dt"
                              },
                              180,
                              "day"
                           ]
                        }
                     ]
                  },
                  true
               ]
            },
            true
         ]
      },
      "Identifier":"VR-UA-0006",
      "Version":"1.0.0",
      "Country":"UA"
   }
]

```

</details>

**Comment by MikeMcC399** [comment]
@vaubaehn 
My guess about the reason is confirmed in the blog https://www.coronawarn.app/en/blog/2021-09-08-cwa-version-2-9/

"Users who get vaccinated with Johnson & Johnson’s vaccine after recovery are an exception. Since only one shot is required for this vaccine, the Corona-Warn-App cannot distinguish between those who have recovered and got vaccinated and those who have been vaccinated normally. In these cases, it always displays full vaccination status after 14 days."

I'm afraid that your other points will be lost here. You would need to post elsewhere if you are requesting any change.

**Comment by dsarkar** [comment]
@MikeMcC399 @vaubaehn @Ein-Tim 

It is a technical problem: The actual JSON scheme makes it impossible to differentiate the case "Recovered and 1/1 &J vaccinated" not only for a the CWA but also for the verifier apps. Scanning both certificates would not help in the current implementation, since the vaccination certificate will be shown as invalid in the first 14 days due to the business rules. The current scheme simply cannot map the case properly.

**Comment by vaubaehn** [comment]
@dsarkar @MikeMcC399 @Ein-Tim 
Thanks for your replies, and confirming the technical issue. But from all I understood, the problem will/could be circumvented with CWA 2.10 with rather much effort: https://github.com/corona-warn-app/cwa-app-android/pull/4001
I hope this 2-step approach (2.9: vaccination for recovered except Johnson&Johnson; 2.10: Johnson&Johnson after recovery could be detected) won't get a nightmare for support teams, due to users complaining about that "discrimination"...

All the best!

(@MikeMcC399 I won't invest any more energy into the subject for now, so I won't request any changes 😉 )

**Comment by dsarkar** [comment]
@vaubaehn 

> I got it now. Even CWA could detect recovery + Johnson&Johnson 1/1, it will not do it, because of the verifier apps...

I think that is crucial point: Only one certificate is verified.
