### ISSUE TITLE
FAQ menu is not useable on iPad Air (4th generation) in horizontal mode

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#1998]
## Where to find the issue
- https://www.coronawarn.app/en/faq/
- https://www.coronawarn.app/de/faq/

## Technical details
- Device name: iPad Air 4. Gen
- iPadOS version: 15.1

**This might also affect other tablets or in general other devices with a similar screen size.**

## Describe the issue
The FAQ menu is not visible/useable on the 4. Gen iPad Air if it's in horizontal mode.
If the device is in landscape mode, everything works.
Here's a screenshot:
<img src="https://user-images.githubusercontent.com/67682506/139956954-49e73f88-0111-4e13-b6eb-8ca357cb2198.png" width="300">

## Suggested change
Fix the issue.

## Additional information
This bug seems to be reproducible using Google Chrome dev tools.

**Comment by MikeMcC399** [comment]
This problem is also reproducible on a desktop version of Google Chrome or Mozilla Firefox. Start with a browser window showing https://www.coronawarn.app/en/faq/ using the full height and width of the screen. Reduce the width of the browser window gradually. The sequence is:

1. Left menu fully visible. All menu items visible.
2. Menu column width reduced. Menu items start to wrap.
3. Menu column width further reduced. Menu items start to wrapped further. Vertical scroll bar appears.
4. Menu column width further reduced. Menu items wrapped and truncated. Horizontal scroll bar appears. (Need to scroll down main window to see horizontal scroll bar of menu items.)
5. Menu column completely collapsed. No horizontal scroll bar visible. No arrow available.
6. Menu column completely collapsed. No horizontal scroll bar visible. Vertical scroll bar for menu items disappears. No arrow available.
7. Arrow appears which, when clicked, overlays the menu items on top of the main window.

The part of the sequence where the menu items are not readable or have disappeared and are not accessible is a problem. On a desktop the problem is not so big because the browser window width can be changed. Setting the window either wider or narrower works around the issue. The user of a mobile device does not have quite this flexibility of changing the width of display.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for your feedback! 

Yes, I also experienced these 3 problems when playing around with this in the Google Chrom dev tool.
Either the arrow to access the menu is shown, then everything is fine, or the menu is cut off, which is not good, or the menu is just not shown at all and one has no chance to access it.

**Comment by Ein-Tim** [comment]
Confirm fixed with the merge of #1999.

Closing as fixed.
