### ISSUE TITLE
`eu_dcc_remove` FAQ entry is out of date

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2030]
## Where to find the issue

- https://www.coronawarn.app/en/faq/#eu_dcc_remove
- https://www.coronawarn.app/de/faq/#eu_dcc_remove

## Describe the issue
The FAQ entry is outdated, under iOS one has to click on "More" and then on "Delete Vaccination Certificate" and then on "Remove Certificate".
These steps are not covered in the FAQ entry. 
Under Android @MikeMcC399 commented below what is out of date.

## Suggested change
Include the steps mentioned above in the FAQ entry.

## Additional information
I will provide a PR fixing this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Please check the steps for Android 2.13 as well if you are proposing a change.

On Android, you have to tap the right arrow after tapping Certificates before you can scroll down.
Then the text is "Remove Certificate", not just "Remove".

**Comment by MikeMcC399** [comment]
Also the question is if the FAQ should cover the instructions for all versions or only for the latest version.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Please check the steps for Android 2.13 as well if you are proposing a change.

Okay, I did not yet receive 2.13 on my Android device but as soon as I have I will check and propose the change with the PR.

[This](https://github.com/corona-warn-app/cwa-website/issues/2030#issuecomment-962485980) question would have to be answered by the Open-Source-Team.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I checked on the current and earlier versions, so I suggest for Android:

https://www.coronawarn.app/en/faq/#eu_dcc_remove
"Android: Tap on the three-dot symbol on the top right of the screen, and then tap on 'Remove Certificate' (or 'Remove' for version 2.9 and earlier)"

https://www.coronawarn.app/de/faq/#eu_dcc_remove
"Android: Tippen Sie auf das drei-Punkte-Icon oben rechts auf dem Bildschirm, und danach auf 'Zertifikat entfernen' (bzw. auf 'Entfernen' für Version 2.9 und früher)

---
The Android UI has been changed quite a few times.
In 2.3 there was no Certificates tab. That came with 2.4. In these two versions the English text was "Delete".
In 2.5 - 2.9 the texts were "Remove" and "Entfernen", also for the confirmation pop-up.
In 2.10 the text changed to "Remove Certificate" and "Zertifikat entfernen". The confirmation texts remained as "Remove" and "Entfernen" though. 
Version 2.11 is not relevant since it is forced updated to the latest version, so any user with an Internet connection can't be using it any more.
Version 2.12 is the same as 2.10.
In Version 2.13.2 which was just released the texts are "Remove Certificate" and "Zertifikat entfernen", also in the confirmation pop-up.

It would make the article very complicated to try to describe all versions accurately, so I don't think that would be good to even try.

I would also not describe the label on the confirmation dialog because that just makes the description more complicated. Also, the main reason for the FAQ is to help users who could not find the function to remove a certificate. Once they find the right place, they don't really need advising about how to complete the confirmation dialog. At least that part is self-explanatory.

**Comment by MikeMcC399** [comment]
Version question raised in https://github.com/corona-warn-app/cwa-website/issues/2032.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I checked on the current and earlier versions, so I suggest for Android:
https://www.coronawarn.app/en/faq/#eu_dcc_remove
"Android: Tap on the three-dot symbol on the top right of the screen, and then tap on 'Remove Certificate' (or 'Remove' for version 2.9 and earlier)"
https://www.coronawarn.app/de/faq/#eu_dcc_remove
"Android: Tippen Sie auf das drei-Punkte-Icon oben rechts auf dem Bildschirm, und danach auf 'Zertifikat entfernen' (bzw. auf 'Entfernen' für Version 2.9 und früher)

Thanks for the suggestion! I will go with your text then! 

---

> It would make the article very complicated to try to describe all versions accurately, so I don't think that would be good to even try.

I agree, also under iOS, the UI since 2.3 changed heavily, thus I am also absolutely against describing all versions in the FAQ entry. 

> I would also not describe the label on the confirmation dialog because that just makes the description more complicated. Also, the main reason for the FAQ is to help users who could not find the function to remove a certificate. Once they find the right place, they don't really need advising about how to complete the confirmation dialog. At least that part is self-explanatory.

Agreed, will change!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Good to hear you agree!
Enjoy your Sunday too!

**Comment by Ein-Tim** [comment]
FYI: A PR is ready, but I found a inconsistency in the iOS implementation and provided a PR which fixes this: https://github.com/corona-warn-app/cwa-app-ios/pull/3803
After this PR is merged, I will provide a PR here, fixing this issue.

**Comment by Ein-Tim** [comment]
As the wording under iOS will change in 2.14 (see https://github.com/corona-warn-app/cwa-app-ios/pull/3803#issuecomment-963903180), I will wait with a PR until things have sorted out.

**Comment by Ein-Tim** [comment]
I'm not certain what exactly will be released with 2.14, so I decided to just describe the implementation in 2.13 and adjust it if necessary with the 2.14 release.

PR will follow tomorrow.
