### ISSUE TITLE
FAQ: Mention that only luca codes generated by businesses (not the user-generated ones) are compatible with CWA

### ISSUE THREAD

**Issue by floscher** [corona-warn-app/cwa-website#2056]
## Where to find the issue
FAQ

## Describe the issue / Suggested change
The FAQ should mention, that QR codes generated by users in their Android/iOS luca-apps ("Meinen QR-Code anzeigen" as well as "privates Treffen erstellen") use different formats that are not compatible with the CWA. Only codes generated by businesses at https://app.luca-app.de/login are compatible.

**Comment by floscher** [comment]
Just noticed in #2055 , that there is already one sentence about private codes: ![](https://user-images.githubusercontent.com/88365935/140950803-2c4d3e60-8e12-48a5-928a-226545aa3955.png)

**Comment by jkrwdf** [comment]
First of all my apologies for raising this issue by a comment in https://github.com/corona-warn-app/cwa-documentation/issues/590. 

Motivated by press announcements, I just tried with what was at hand (and this was a private Luca meeting), failed, quickly checked the FAQ and simply missed the last sentence of the red marked part above.

A suggestion (I know it's wrong in this repo): If the CWA could at least recognize all formats of Luca QR codes, instead of the generic messsage "Kein geeigneter QR-Code - Der QR-Code wird nicht von der Corona-Warn-App unterstützt. Bitte wählen Sie einen geeigneten Code" a particular message for the (certainly frequent) cases like "Luca code too old < 25.5." could be issued. If I would have seen "Luca QR codes for private meetings cannot be used in CWA" I would not have supposed an error.

**Comment by floscher** [comment]
@jkrwdf No need to apologize, that passage was added to the FAQ in #2055 **after** you commented over there (that's where I got the image from, the red border marks the changed parts). And even if it was there before, I think this should be made clearer, because I would not expect everyone to notice that short sentence at the end.

**Comment by MikeMcC399** [comment]
@floscher 

- Is this issue still relevant? 
- see also https://github.com/corona-warn-app/cwa-website/issues/2751

**Comment by floscher** [comment]
@MikeMcC399 As far as I know the other types of QR codes (for private meetings and keychain  badges) are no longer used by luca. Only the QR codes generated by businesses are left, which should still be compatible.

So this issue could be closed, since only compatible codes remain in use. But it should be noted somewhere that you can still check in with the CWA. But there's other issues for that.
