### ISSUE TITLE
Missing (blog) announcement that CWA now informs about BMG recommended boosters 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2121]
## Where to find the issue
- https://www.coronawarn.app/de/blog/2021-11-04-cwa-booster-notification/
- https://www.coronawarn.app/en/blog/2021-11-04-cwa-booster-notification/
- https://www.coronawarn.app/de/faq/#vac_cert_booster_info (also out of date as BMG recommendations are also send)
- https://www.coronawarn.app/en/faq/#vac_cert_booster_info (also out of date as BMG recommendations are also send)

## Describe the issue
CWA is also sending out booster notifications to everyone who is included in the recommendation from the BMG. This makes a lot of the stuff written in the FAQ entries linked from https://www.coronawarn.app/de/faq/#vac_cert_booster outdated. 
Also, there was no announcement about this change. 

## Suggested change
Update the FAQ section and announce this change!

**Comment by Ein-Tim** [comment]
@dsarkar or/and @larswmh 

Will you be able to take a look at this soon?

**Comment by MikeMcC399** [comment]
@Ein-Tim's comment that booster notifications from the Federal Ministry of Health are also being provided, in addition to ones from STIKO, is still true today. There has however been no update made to the FAQ which makes no mention of recommendations from BMG:

https://www.coronawarn.app/en/faq/#vac_cert_booster_info

"The Corona-Warn-App (CWA) will notify the user to consider a booster vaccination if certain conditions are met. These conditions are based on the recommendations of the Paul Ehrlich Institute and the Permanent Vaccination Commission (STIKO) of the Robert Koch Institute (RKI)."

`BNR-DE-0300` from https://distribution.dcc-rules.de/bnrules

says:

"The Federal Ministry of Health recommends that all persons who have not had a proven case of the coronavirus (SARS-CoV-2) and who obtained their base vaccination more than six months ago arrange a vaccination appointment or discuss the benefits of getting a booster shot with their doctor. Scientific studies confirm that booster shots provide a higher level of protection against becoming infected with COVID-19. As your saved certificates indicate that you belong to this group of persons and have not yet received a booster shot, we would like to inform you of this recommendation. (Rule BNR-DE-0300) This notification is exclusively based on the certificates stored on your smartphone. The data was processed on your smartphone. No data was transferred to the RKI or third parties."

"Das Bundesministerium für Gesundheit (BMG) empfiehlt allen Personen, bei denen keine Infektion mit dem Coronavirus SARS-CoV-2 nachgewiesen wurde und deren Grundimmunisierung über 6 Monate her ist, einen Impftermin zu vereinbaren bzw. sich über den Nutzen einer Auffrischimpfung ärztlich aufklären zu lassen. Wissenschaftliche Studien belegen die höhere Schutzwirkung von Auffrischimpfungen vor einer COVID-19-Infektion. Da Sie laut Ihrer gespeicherten Zertifikate dieser Personengruppe angehören und noch keine Auffrischimpfung erhalten haben, möchten wir Sie auf diese Empfehlung hinweisen. (Regel BNR-DE-0300) Dieser Hinweis basiert ausschließlich auf den auf Ihrem Smartphone gespeicherten Zertifikaten. Die Verarbeitung der Daten erfolgte auf Ihrem Smartphone. Es wurden hierbei keine Daten an das RKI oder Dritte übermittelt."

- This issue is also related to https://github.com/corona-warn-app/cwa-documentation/issues/754 regarding the technical implementation of the booster notification rules not being updated to the STIKO announcements.

## Suggested change

Update 
- https://www.coronawarn.app/en/faq/#vac_cert_booster_info "How do I become aware of booster vaccinations in the context of Corona?"
-  https://www.coronawarn.app/de/faq/#vac_cert_booster_info "Wie erfahre ich von Auffrischimpfungen im Kontext von Corona?"

to add "Federal Ministry of Health" / "Bundesministerium für Gesundheit (BMG)" as source of booster recommendations to conform with the text transmitted in `Rule BNR-DE-0300`.

**Comment by Ein-Tim** [comment]
@dsarkar Will you address this issue soon? It's now open for more than 4 months, without any feedback from the team.

**Comment by dsarkar** [comment]
@Ein-Tim Would you like to provide a PR with your suggestion? Then I would get internal review and possibly approval for this change. Thanks.

**Comment by Ein-Tim** [comment]
After assessing the situation I think there are meanwhile no recommendations for booster vaccinations anymore from the BMG.
Everything is covered by the STIKO, but the rules which CWA sends at the moment are so out of date that they still talk about recommendations from the BMG.

I did not find any recommendations for boosters only from the BMG anymore.
Here's a link to the page "Aktuelle Informationen zur COVID-19-Impfung", specially to the paragraph "Auffrischungsimpfung": https://www.bundesgesundheitsministerium.de/coronavirus/faq-covid-19-impfung.html#c23765

@MikeMcC399 Maybe you could double check this when you have time but I did not found any boosters recommended by the BMG but not by the STIKO at the moment.

If this is actually the case I'd like to wait for the updated booster notification rules and see whether they still include a booster recommendation from the BMG.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- I don't really know what @dsarkar's expectation is, if he is encouraging you to submit a PR. He would have to say that himself and it was unclear whether you were suggesting to submit a PR for a blog post, FAQs or both.

- Until there is some concrete news from RKI / Open Source Team about changes to the booster rules used in CWA I don't think it makes sense to have a new blog announcement. In any case the information needs to come from them as an official source, not from the community. I can't see any recent feedback in https://github.com/corona-warn-app/cwa-documentation/issues/754 about content or time frames for booster recommendation changes.

- For the FAQs I don't know what could be changed in the FAQs if here the BMG booster recommendation used in the app is not aligned with BMG's web content.

**Comment by Ein-Tim** [comment]
CWA will (hopefully) soon not send any booster notification for BMG recommended boosters anymore, so this issue's obsolete and now closed.
