### ISSUE TITLE
Datenschutzfolgeabschätzung was not updated since version 1.15

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2245]
## Where to find the issue
https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf

## Describe the issue
The Datenschutzfolgeabschätzung was not updated since 12.07.2021 (Version 1.15), however, we already reached version 2.15 now.

## Suggested change
Update the Datenschutzfolgeabschätzung. 

---
Internal Tracking ID: [EXPOSUREAPP-11118](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11118)

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-website/pull/2250

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11118](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11118)

**Comment by Ein-Tim** [comment]
With PR #2250 an updated version of the document was added, however, it still does not include features added in e.g. version 2.15., as it shows 09.12.2021 as last updated.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The [Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland Öffentliche Version -Version 1.20, 09.12.2021](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) contains a table on page 4 which says "1.20 Berücksichtigung der App-Releases
V2.11, V2.12, V2.13, V2.14 und V2.15".

In the text of the document it also specifically refers to the app version 2.15, for instance:

"Mit Release 2.15 wird die CWA um die Funktion zum Nachweis von gespeicherten COVID-Zertifikaten im Rahmen von Online-
Validierungsverfahren bei Drittanbietern (z. B. Reise- und Veranstaltungsunternehmen) erweitert."

It seems that your issue is in fact resolved.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, you're right! Thank you! 

Closing this issue as fixed.
