### ISSUE TITLE
R 2.16 FAQ Update #international_phone_numbers: Update TAN hotline time

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2294]
## Where to find the issue

https://www.coronawarn.app/de/faq/#international_phone_numbers
https://www.coronawarn.app/en/faq/#international_phone_numbers

## Describe the issue

see https://github.com/corona-warn-app/cwa-app-android/pull/4666

## Suggested change

Mo – Sa: 07:00 – 22:00 Uhr for TAN request
Mo–So: 07:00 – 20:00 Uhr for Kundenservice

EDIT:
Mo–So: 07:00 – 20:00 Uhr for TAN 
no change  for technical hotline 

To be confirmed...

---
Internal Tracking ID: [EXPOSUREAPP-11102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11102)

**Comment by Ein-Tim** [comment]
@dsarkar 

So a TAN can't be requested on Sundays anymore, but the "Kundenservice" is available? Or is this an issue in your OP?

**Comment by MikeMcC399** [comment]
@dsarkar 

I'm confused because PR https://github.com/corona-warn-app/cwa-app-android/pull/4666 only changes the TAN hotline  (0800 7540002) availability hours, not the Technical hotline (0800 7540001).

`submission_contact_operating_hours_body`

"Unser Kundenservice ist in den folgenden Sprachen für Sie da: Deutsch, Englisch, Türkisch 
Erreichbarkeit:\nMo–So: 07:00 – 20:00 Uhr"

---
Currently https://www.coronawarn.app/en/faq/#international_phone_numbers says:

Technical Hotline

The technical hotline will help you with technical questions about the Corona-Warn-App, for instance if you have problems with the exposure logging. It is available Monday to Saturday from 7 a.m. to 10 p.m. German local time (except on national holidays)

National: 0800 7540001

International: +49 30 498 75401

TAN Hotline

The TAN hotline will help you to enter the TAN if you have a positive PCR test result and if you have not received a TAN or document with a PCR-Test QR code. The TAN hotline is available 24 hours a day, seven days a week.

National: 0800 7540002

International: +49 30 498 75402

---

So the TAN hotline changes from 24/7 to Monday - Saturday 07:00 to 20:00.
There is no change to the Technical hotline (I believe) which stays at Monday to Saturday 07:00 to 22:00

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim I will clarify internally.

**Comment by MikeMcC399** [comment]
@dsarkar 
> I will clarify internally.

Good idea! Also from what date onwards is the change supposed to be effective?

**Comment by MikeMcC399** [comment]
Note also that the times are listed in:

- #who_can_help as well as in
- #international_phone_numbers

So both articles (in both languages) would need to be changed.

**Comment by MikeMcC399** [comment]
From CWA Android 2.16.0-RC6 displaying German language, since translations have not been done yet.

---
Three-dot icon > App-Informationen > Technische Hotline

![Technische Hotline](https://user-images.githubusercontent.com/66998419/148573738-405e9f77-1fc6-40bf-af00-4f6e7b27f09b.png)

---
Status > "Sie lassen sich testen?" > TAN für PCR-Test anfragen

![TAN Hotline](https://user-images.githubusercontent.com/66998419/148573757-81180ef5-d267-4712-ac84-e66cc50a1724.png)

**Comment by Ein-Tim** [comment]
So just that I get it right, the technical hotline will be available until 22:00h, while the TAN hotline will close at 20:00h. This doesn't sound correct to me, wouldn't it make more sense the way around?

**Comment by dsarkar** [comment]
@Ein-Tim Will check internally.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> So just that I get it right, the technical hotline will be available until 22:00h, while the TAN hotline will close at 20:00h. This doesn't sound correct to me, wouldn't it make more sense the way around?

Do you have some information about the call distribution (demand) over time for the two hotlines? If not, then how do you want to make suggestions about the "right" opening times?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Of course I don't have any insights you don't have. And actually, this was just my first reaction:
"Why can I ask some question at 21:30h but not get a TAN for warning others?". 
But, yes, I assume the hotline team performed an analysis when most people call and decided the change in opening hours based on this analysis.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Perhaps @dsarkar will be able to provide some background information about the decision for the change when he confirms the opening hours? After I wrote my question to you I realised we don't know at all what were the factors for the decision.

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Change will come into effect on 16.01.2022. I have further information about the decision process.

**Comment by MikeMcC399** [comment]
@dsarkar 
- Would you like to update the title to include the word "TAN"?<br>
"Update TAN hotline time"

- I have made the same request to the Android PR https://github.com/corona-warn-app/cwa-app-android/pull/4666
