### ISSUE TITLE
R 2.16 FAQ - update #root_detection_android 

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2300]
## Where to find the issue

https://www.coronawarn.app/de/faq/?search=root#root_detection_android 
https://www.coronawarn.app/en/faq/?search=root#root_detection_android 

## Describe the issue

Version 2.12 introduced the display of a security notice if administrator rights are active on your smartphone. You can now suppress this notice until the next update.

## Suggested change

Change: 

"Sie werden diesen Hinweis immer dann erhalten, wenn Sie die App neu starten, neu installieren oder updaten."

to

"Sie werden diesen Hinweis immer dann erhalten, wenn Sie die App neu starten, neu installieren oder updaten.
Diese Warnungen können ab dem Release 2.16 bis zum nächsten Update der App unterbunden werden."

---
Internal Tracking ID: [EXPOSUREAPP-11102](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11102)

**Comment by Ein-Tim** [comment]
I recommend to change "unterbunden" to "unterdrückt". It sounds better IHMO.

**Comment by MikeMcC399** [comment]
@dsarkar 

Perhaps integrate the text as is used in the app?

From https://github.com/corona-warn-app/cwa-app-android/blob/release/2.16.x/Corona-Warn-App/src/main/res/values/release_info_strings.xml#L28

"Since Version 2.12, a security notification is displayed if administrator rights are active on your smartphone. You can hide this notification until the next update."

https://github.com/corona-warn-app/cwa-app-android/blob/release/2.16.x/Corona-Warn-App/src/main/res/values-de/release_info_strings.xml#L29

"Mit Version 2.12 wurde die Anzeige eines Sicherheitshinweises eingeführt, falls auf Ihrem Smartphone Administratorrechte aktiv sind. Diesen Hinweis können Sie nun bis zum nächsten Update unterdrücken."

---
https://www.coronawarn.app/en/faq/#root_detection_android

"You will receive this notice whenever you restart, reinstall or update the app. Version 2.16 of the app and later allows you to hide this notification until the next update." 

---
https://www.coronawarn.app/de/faq/#root_detection_android

"Sie werden diesen Hinweis immer dann erhalten, wenn Sie die App neu starten, neu installieren oder updaten. Ab Version 2.16 können Sie den Hinweis bis zum nächsten Update unterdrücken."

**Comment by MikeMcC399** [comment]
This is now put into PR #2302.

@dsarkar 

- You should take a look if you want to follow the above suggestions and influence the content of PR #2302.
