### ISSUE TITLE
Analysis page bug: If not the standard time range is used, wrong dates are shown

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2414]
## Where to find the issue
- https://coronawarn.app/de/analysis
- https://coronawarn.app/en/analysis

## Technical details
- Browser used: Safari 15.3 (17612.4.9.1.5)
							Edge Version 98.0.1108.43 (Offizielles Build) (arm64)
- Machine: MacBook Air 2020
- macOS version 12.2 (21D49)

## Describe the issue
The analysis page shows wrong dates, if the user adjusts the time range shown:

https://user-images.githubusercontent.com/67682506/152611941-501f03db-a688-4e96-b0f5-f44e48bb20f6.mov

## Suggested change
Fix the bug.

**Comment by MikeMcC399** [comment]
@Ein-Tim

The problem you describe is reproducible, also on Google Chrome.

1. Open https://www.coronawarn.app/en/analysis/
2. Take default "Last 28 days" and "Daily" display
3. Note that month and day of the month on the X-axis are correctly displayed
4. Click the Time range and set the first day to one day earlier
5. Click apply
6. Note the the X-axis now shows month and year instead of month and day of the month

**Last 28 days**

![Last 28 days](https://user-images.githubusercontent.com/66998419/152640419-7e320f42-8c4f-40da-9bb3-28157aee25b0.jpg)

**Last 29 days**

![Last 28 days plus one](https://user-images.githubusercontent.com/66998419/152640433-abf2290a-8c7e-4054-9c54-a571bca344ed.jpg)

Please consider posting static screenshots instead of movies. For me they are easier to view and mark up.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Please consider posting static screenshots instead of movies. For me they are easier to view and mark up.

Noted, thanks for your feedback!

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks and same to you!

The problem seems to be that there are just two modes of labelling the X-axis.
- Month / day of month for 28 days or less
- Month / year for 28 days or more

This does not always make good use of the space available.

For a full-screen view of a single graph on a wide screen and selecting six months, the labels are also not optimal, with the month/year label repeated 3 or 4 times.

See for instance October 2021 in the attached screenshot shown 4 times.

![image](https://user-images.githubusercontent.com/66998419/152640864-2cc4ab4d-ad61-4bee-a359-177edd79f246.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
Will this dashboard axis-labelling issue be fixed?

![image](https://user-images.githubusercontent.com/66998419/157608376-a40a963d-a14f-4aba-9192-7afd9e962ee9.png)

**Comment by Ein-Tim** [comment]
Confirm fixed with #2717. 

Thank you, enjoy the weekend!

**Comment by MikeMcC399** [comment]
In the steps from https://github.com/corona-warn-app/cwa-website/issues/2414#issuecomment-1030605994, the dates are now correctly labelled:

![image](https://user-images.githubusercontent.com/66998419/162667647-08353707-4445-4302-88a1-0941756cc9bd.png)

Also from https://github.com/corona-warn-app/cwa-website/issues/2414#issuecomment-1030608111:

![image](https://user-images.githubusercontent.com/66998419/162667838-face41b5-0e0d-41c6-b7bb-b12dc576d666.png)

It seems there is nothing preventing this issue from being closed now.
