### ISSUE TITLE
Release 2.20 updates

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#2539]
See PR https://github.com/corona-warn-app/cwa-website/pull/2540

Internal Tracking ID: [EXPOSUREAPP-11957](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11957)

**Comment by Ein-Tim** [comment]
FAQ needs to be updated reg. availability of the technical hotline, see https://github.com/corona-warn-app/cwa-app-ios/pull/4346.

**Comment by Ein-Tim** [comment]
Hey @dsarkar 

Both iOS and Android will be able to fetch the days the app considers from the server with version 2.20. 

There are many FAQ entries and other places all over the website where it is stated that the app considers the last 14 days. All these would have to be updated. 

As it is not promised that there won't be another change to days the app considers, I suggest to implement a central-managed variable in the https://github.com/corona-warn-app/cwa-website/blob/master/gulpfile.js similar to the one we already have for the app & OS versions.

If you think this is a good idea: Give me an OK and I will prepare a PR merging into https://github.com/corona-warn-app/cwa-website/pull/2434.

I would just need a GO today or tomorrow so that I can do this on the week-end to not block your work on https://github.com/corona-warn-app/cwa-website/pull/2434.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Please, fell free to add your opinion: Do you think a central-managed variable fro the days the app takes into account makes sense? I gave some reasons why I think so in https://github.com/corona-warn-app/cwa-website/issues/2539#issuecomment-1072601053.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

It's true that 14 days appears in a lot of places, however many of these instances are for other things like vaccination.

It will require manual review of the FAQ when version 2.20 is released to judge exactly which appearances of 14 days have to be changed. For instance, the app will not affect the number of days which GAEN stores. For Google this will officially stay at 14 days, according to the Google UI (see also https://github.com/corona-warn-app/cwa-app-android/issues/1020).

At this time I would not parameterize these values. I would wait until the release of 2.20. I can't really judge how often this parameter might change in the future, but I would suspect that it will not change again.

**Comment by Ein-Tim** [comment]
Okay, thanks @MikeMcC399, you're right that often the 14 days are mentioned in combination with vaccination protection & that GAEN will continue to store 14 days.

I did not start working on a PR and would like to get feedback from the Open-Source-Team before doing anything.

I'm pinging @svengabr now, as he initially added the other parameters in the gulpfile, if I remember correctly.

**Comment by MikeMcC399** [comment]
@dsarkar 

2.20 has been released, so this issue can probably be closed now.
