### ISSUE TITLE
Most links to the FAQ do not work

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2582]
## Where to find the issue
- https://coronawarn.app/de/faq
- https://coronawarn.app/de/faq

## Describe the issue
I shared multiple links to FAQ entries on my Twitter account. These links do not work anymore, after the new FAQ went online now.

For example, click on the link I shared in this Tweet: https://twitter.com/eintim2/status/1503766871648129031?s=21&t=pXa5LKOSdTWfKSwa8QRXqg.

It doesn't work anymore. 

The FAQ section I linked to is/was: https://www.coronawarn.app/de/faq/#risk_assessment.

## Suggested change
There should definitely be a backwards compatibility here.

---
Internal Tracking ID: EXPOSUREAPP-12446

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I agree that all previously valid links must continue to work.

For https://www.coronawarn.app/de/faq/#risk_assessment there are now two sections with this title:

- https://www.coronawarn.app/de/faq/results/#app_features_risk_assessment
- https://www.coronawarn.app/de/faq/results/#technical_correlations_risk_assessment

**Comment by MikeMcC399** [comment]
The link https://www.coronawarn.app/en/faq/#glossary no longer displays the Glossary. It just displays the complete FAQ with the Glossary at the bottom.

**Comment by MikeMcC399** [comment]
I checked all section heading links from the previous FAQ to see whether they worked in the new FAQ. Most of them no longer work. See "no" in the table below:

Old section anchor | works in new FAQ
--- | ---
[#in_short](https://www.coronawarn.app/en/faq/#in_short) | no
[#support](https://www.coronawarn.app/en/faq/#support) | no
[#news](https://www.coronawarn.app/en/faq/#news) | no
[#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) | no
[#test_cert](https://www.coronawarn.app/en/faq/#test_cert) | no
[#vac_cert](https://www.coronawarn.app/en/faq/#vac_cert) | no
[#val_service](https://www.coronawarn.app/en/faq/#val_service) | yes
[#rapid_antigen_test](https://www.coronawarn.app/en/faq/#rapid_antigen_test) | yes
[#check_in](https://www.coronawarn.app/en/faq/#check_in) | no
[#most_asked](https://www.coronawarn.app/en/faq/#most_asked) | no
[#background_updates](https://www.coronawarn.app/en/faq/#background_updates) | yes
[#notification](https://www.coronawarn.app/en/faq/#notification) | no
[#availability](https://www.coronawarn.app/en/faq/#availability) | yes
[#application](https://www.coronawarn.app/en/faq/#application) | no
[#risk_assessment](https://www.coronawarn.app/en/faq/#risk_assessment) | yes
[#general](https://www.coronawarn.app/en/faq/#general) | yes
[#open-source](https://www.coronawarn.app/en/faq/#open-source) | no
[#privacy_security](https://www.coronawarn.app/en/faq/#privacy_security) | yes
[#resolved](https://www.coronawarn.app/en/faq/#resolved) | yes
[#glossary](https://www.coronawarn.app/en/faq/#glossary) | no


- Particularly the [#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) anchor **must** work because it is embedded in the app. See also https://github.com/corona-warn-app/cwa-website/issues/2577.

- The other links ought to work as well, because they may have been bookmarked or quoted as solutions to people's issues.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, that's great! Enjoy your Sunday evening!

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-12446

**Comment by MikeMcC399** [comment]
Here is the table from https://github.com/corona-warn-app/cwa-website/issues/2582#issuecomment-1079972577 listing the links requiring attention. I will edit the checkboxes when the new FAQ provides backwards compatibility for each of them:

- [ ] [#in_short](https://www.coronawarn.app/en/faq/#in_short) 
- [ ] [#support](https://www.coronawarn.app/en/faq/#support) 
- [ ] [#news](https://www.coronawarn.app/en/faq/#news) 
- [ ] [#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) 
- [ ] [#test_cert](https://www.coronawarn.app/en/faq/#test_cert) 
- [ ] [#vac_cert](https://www.coronawarn.app/en/faq/#vac_cert) 
- [ ] [#check_in](https://www.coronawarn.app/en/faq/#check_in) 
- [ ] [#most_asked](https://www.coronawarn.app/en/faq/#most_asked) 
- [ ] [#notification](https://www.coronawarn.app/en/faq/#notification) 
- [ ] [#application](https://www.coronawarn.app/en/faq/#application) 
- [ ] [#open-source](https://www.coronawarn.app/en/faq/#open-source) 
- [ ] [#glossary](https://www.coronawarn.app/en/faq/#glossary)

**Comment by MikeMcC399** [comment]
@svengabr 

You have closed this issue, however I don't see a resolution for the following:

- [ ] [#news](https://www.coronawarn.app/en/faq/#news) 
- [ ] [#notification](https://www.coronawarn.app/en/faq/#notification) 

Could you perhaps cross-check?

**Comment by MikeMcC399** [comment]
The remaining two missing anchors #news and #notification have been added.

- #news is resolved through https://github.com/corona-warn-app/cwa-website/pull/2682
- #notification is resolved through https://github.com/corona-warn-app/cwa-website/pull/2679
