### ISSUE TITLE
FAQ entries are no longer expanded if linked to via anchor link (e.g. from inside the app)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2584]
## Where to find the issue
- https://www.coronawarn.app/de/faq/
- https://www.coronawarn.app/en/faq/

## Describe the issue
If a FAQ entry is linked to using an anchor link, the entry is no longer expanded so that the user can see the content of this FAQ entry. This is suboptimal, as it completely differs from the behavior of the old FAQs, where only the FAQ entry which is linked to was open, while all other entries where closed. 

## Suggested change
Reintroduce the behavior of the old FAQ version.

## Screen recording

To help understanding the problem, here's a screen recording: 

https://user-images.githubusercontent.com/67682506/160196233-b07c8e41-0ddc-4ced-9304-38e15c57a406.mp4

---
Internal Tracking ID: EXPOSUREAPP-12449

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- This issue is very closely related to https://github.com/corona-warn-app/cwa-website/issues/2577

To workaround it, turn the mobile device into landscape orientation, then tap on the FAQ link. Provided the browser is being shown in landscape orientation then the article should open.

Several different problems appear when the available browser window width is narrow, like on a mobile device in portrait mode. The problems can also be seen on a desktop if the browser window width is minimized.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I think this is another issue, as the page scrolls to the correct entry in the FAQs, however, the entry itself is not expanded.

The issue you reported & I confirmed in #2577 is another one, that only the footer of the website is shown and not the actual FAQ entry.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- You're right that it is a different issue here. It may just turn out to have the same root cause as #2577. We'll have to wait until the experts take a look.

- I'll try to make a list of other places in the Android app where the FAQ is accessed. I expect they will all fail, so I won't open separate issues for the moment if I find other links failing.

**Comment by MikeMcC399** [comment]
- I added a new table to https://github.com/corona-warn-app/cwa-website/issues/2577#issuecomment-1079655543 to cover the different failure cases.

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-12449

**Comment by Ein-Tim** [comment]
Closing as fixed with https://github.com/corona-warn-app/cwa-website/pull/2645
