### ISSUE TITLE
The new FAQ search does not filter as good as the previous one

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2591]
## Where to find the issue
- https://www.coronawarn.app/en/faq
- https://www.coronawarn.app/de/faq

## Describe the issue

The new search of the FAQs is really bad IMO. Instead of showing the entry which the user is searching for, it shows the section in which the entry is included & in this section, the user has to search for the entry themself.
This is so much worse than prior to the FAQ redesign. Even I am lost in all these entries and don't find the information I know exists. 

## Steps to reproduce this issue

1. In the search field, type "When do I receive my PCR test result in the app?"
2. See that the page shows: "FAQ   / Search result: 2 results found"
3. See that the sections "App features" & "What to do, if?" are displayed. 
4. Click on the sections "App features" 
5. Notice that you see all entries in this section and not only the one with the title "When do I receive my PCR test result in the app?"

## Suggested change
Restore the behavior of the old FAQ page where only the entries are shown which include the searched keyword & not also all other entries in the same section.

---
Internal Tracking ID: EXPOSUREAPP-12450

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- The problem occurs on a mobile device in portrait orientation. A temporary workaround is to turn the device into landscape orientation.

- How about changing the title to "FAQ search result not expandable" as "really bad" is not a technical description and other readers will not know exactly what this is about just by reading the title?

---
- It's always easy in hindsight, but it seems that the PR https://github.com/corona-warn-app/cwa-website/pull/2434 was not tested well enough. It was in Draft state for quite a while, which means that reviews were not requested during that time. It probably should have been frozen first and then left for testing for several days before merging. Then merging on a Friday morning before the weekend without developers / support available over the weekend turned out to be risky. On top of that, the Cypress tests didn't pick up the major problems we're seeing (see https://github.com/corona-warn-app/cwa-website/issues/2585 for an enhancement request).

**Comment by Ein-Tim** [comment]
> How about changing the title to "FAQ search result not expandable" as "really bad" is not a technical description and other readers will not know exactly what this is about just by reading the title?

The issue here is not that the entries are not expandable but that the content is not filtered well enough, IMO.

See 5. in the Steps to reproduce section of my OP.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> The issue here is not that the entries are not expandable but that the content is not filtered well enough, IMO.

In that case I am seeing a different issue, so I will open a new issue for this with description, screenshots and steps to reproduce. Probably a lot of these problems are interrelated.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I also think so. In general I observe that the behavior is mostly good / acceptable on my desktop, but not on a mobile phone.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I see now that this issue is about too many articles being shown after expanding the search results section header.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

The search result counters are incorrect in portrait orientation:

![image](https://user-images.githubusercontent.com/66998419/160281360-ea7321a8-8549-4724-a911-1029ea5813da.png)

They show up correctly in landscape orientation:

![image](https://user-images.githubusercontent.com/66998419/160281401-7269090c-14c3-4706-8c9d-adf5d283e436.png)

**Comment by svengabr** [comment]
Indeed an unlucky title for this issue. However, we are always open to constructive feedback. I did create a Jira ticket and a developer will take a look at this.

Internal Tracking ID: EXPOSUREAPP-12450

**Comment by Ein-Tim** [comment]
@svengabr

I want to apologize, this was not a constructive issue title, I changed it now.

Sorry again, I hope you know that this was nothing against you or your team!

Thanks for looking at this issue!

**Comment by svengabr** [comment]
@Ein-Tim a PR with a possible fix for this issue was merged. Could you please check if this resolved your problem? Thank you!
