### ISSUE TITLE
x symbol of FAQ search overlaps with search term

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2593]
## Where to find the issue
- https://www.coronawarn.app/en/faq
- https://www.coronawarn.app/de/faq

## Describe the issue
The search term and the "x" symbol of the search box may overlap, if the search term is long enough.

![image](https://user-images.githubusercontent.com/67682506/160275662-b3c5d8ed-7a48-4ffd-95a4-8d85126ebc8e.jpeg)

## Suggested change
Content should not overlap, assign the "x" icon to always be at the top of all other content.

---
Internal Tracking ID: EXPOSUREAPP-12451

**Comment by MikeMcC399** [comment]
I can reproduce this in Google Chrome Desktop with Samsung Galaxy A51/71 selected in Developer tools.

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-12451

**Comment by Ein-Tim** [comment]
Closing as fixed.

**Comment by MikeMcC399** [comment]
@svengabr

> the PR for this issue was already merged. Could you check if this has resolved your problem?

- I confirm that the issue is resolved. There is just a remaining issue if the window is resized. See https://github.com/corona-warn-app/cwa-website/issues/2601.

![image](https://user-images.githubusercontent.com/66998419/160583460-fc6a22ce-2a74-42ae-8762-c62f040096af.png)

Pressing F5 (refresh) is a workaround for this other issue.
