### ISSUE TITLE
Most links to the blog from the FAQ are broken

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2609]
## Where to find the issue
- https://www.coronawarn.app/de/faq/
- https://www.coronawarn.app/en/faq/

## Describe the issue
All links from the FAQ to the blog are broken. Try e.g. https://www.coronawarn.app/en/faq/results/#check_in_luca_scan. You will only get a 404. 

## Suggested change
Fix the issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This is quite bad! It's good that you caught it.

Some links from the FAQs to Blog articles work, others do not.

1. Working link from https://www.coronawarn.app/en/faq/results/#risk_encounter_place to https://www.coronawarn.app/en/blog/2022-01-21-cwa-uhrzeit-rote-kachel/
2. Non-working link from https://www.coronawarn.app/en/faq/results/#eu_dcc_which to https://www.coronawarn.app/en/en/blog/2021-06-10-cwa-version-2-3 (404 error)

This is due to constructs with `../` being used which are affected by changes in the web structure.

Also there is a problem with the Cypress tests because they didn't find the issue. The Cypress test suite passes. 🙁  I will investigate this second point and open a separate issue for Cypress.

**Comment by Ein-Tim** [comment]
I'm on my way fixing this issue. PR follows in ca. 15 min.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I would appreciate it if you could take a look at #2610!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Please take a look at the new issues:

- #2611 
- #2612 
- #2613

I will not do any more on this today. 
- There are more links to be corrected than you have addressed in #2610.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you! 

> I will not do any more on this today.

Understandable, enjoy your evening!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I looked at this PR with an updated Cypress test. Unfortunately it does not fix all blog issues.

I made a suggestion for resolution in https://github.com/corona-warn-app/cwa-website/issues/2611#issuecomment-1081432894.

I think it would be preferable to fix all issues involving bad relative links in one PR. Before doing that it really makes sense to update the Cypress tests. Nobody can sensibly test this number of changes by hand, so we need test automation to cover the new pages.

**Comment by Ein-Tim** [comment]
PR #2610 closed in favour of PR #2617.

**Comment by Ein-Tim** [comment]
PR https://github.com/corona-warn-app/cwa-website/pull/2617 fixed this issue.

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/faq/results/#check_in_luca_scan now contains a working link to https://www.coronawarn.app/en/blog/2021-10-11-cwa-most-important-features/
