### ISSUE TITLE
Add lock file of a node package manager

### ISSUE THREAD

**Issue by LarsVomMars** [corona-warn-app/cwa-website#27]
Push the `yarn.lock` file to the repo leading to faster install times and better version control of the installed packages with yarn.

**Comment by hangy** [comment]
The developer instructions and workflows seem to use `npm install`, so that seems to be the preferred package manager.

- https://github.com/corona-warn-app/cwa-website/blob/14ef9e3a6eef405785b2a29715b5a86a8a0a05b4/README.md#L35
- https://github.com/corona-warn-app/cwa-website/blob/b1b3828cb90f0ba7fba587692398a9e8463c0c6d/.github/workflows/deploy-master.yml#L24
- https://github.com/corona-warn-app/cwa-website/blob/1e2af038bb42e390632fff62f272992e7fc9acb0/.github/workflows/build.yml#L24

➡️ Add `package-lock.json` instead of `yarn.lock`?

**Comment by ulrichstark** [comment]
Sounds reasonable,
but it is listed in .gitignore right now...

https://github.com/corona-warn-app/cwa-website/blob/3849875c7db2407bdf0f76ad8d08c14750800877/.gitignore#L43

should i create a PR to remove it?

**Comment by LarsVomMars** [comment]
Yeah, you should always push those lock files

**Comment by hangy** [comment]
> Yeah, you should always push those lock files

[Agreed](https://docs.npmjs.com/files/package-locks#using-locked-packages). It could also be interesting to use [`npm ci`](https://medium.com/better-programming/npm-ci-vs-npm-install-which-should-you-use-in-your-node-js-projects-51e07cb71e26) for the GitHub workflows. One idea of this is to ensure that ci/cd workflows use the same package versions of all (also transitive) dependencies as a developer does on their local machine.
