### ISSUE TITLE
luca app announces it is on stand-by

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2751]
## Your Question

According to https://www.luca-app.de/luca-digitale-plattform-fuer-buergerinnen/ luca has gone into stand-by.

- Are any changes necessary to the articles in the section https://www.coronawarn.app/en/faq/results/#check_in_luca?
- ~~Should the PR https://github.com/corona-warn-app/cwa-website/pull/2164 be processed or closed?~~

At least https://www.coronawarn.app/en/faq/results/#check_in_luca_why_now is outdated.

---
Internal Tracking ID: [EXPOSUREAPP-12828](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12828)
Internal Tracking ID: [EXPOSUREAPP-12850](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12850)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for raising this topic.

Affected articles: 15

EN
Is it possible to check in using the CWA to scan Event QR codes from other apps?
Can the Corona-Warn-App read and process the QR codes from luca?
Can luca also read and process QR codes from the Corona-Warn-App?
Can users of the luca app be alerted if CWA users test positive?
Can all QR codes for check-in be read immediately by the Corona-Warn-App and the luca app?
How does the collaboration between the Corona-Warn-App and luca work?
Do app users need to change settings on their smartphones?
What happens when QR codes are scanned by the Corona-Warn-App?
How else do the Corona-Warn-App and luca app differ when it comes to check-in/event registration?
Why was joint use implemented?
Why is luca QR code joint use coming now?
Is the data of the users of the Corona-Warn-App still secure?
What data is transferred from the CWA to luca?
Do we now only need one app for event registration?
Do users need to install both apps for it to work?

DE
Kann man mit der CWA einchecken, indem man Event-QR-Codes anderer Apps scannt?
Kann die Corona-Warn-App die QR-Codes von luca lesen und verarbeiten?
Kann auch luca die QR-Codes der Corona-Warn-App lesen und verarbeiten?
Können Nutzende der luca-App gewarnt werden, wenn CWA-Nutzende positiv getestet wurden?
Können alle QR-Codes zum Check-in sofort von der Corona-Warn-App und der luca-App gelesen werden?
Wie funktioniert die Zusammenarbeit von der Corona-Warn-App und luca?
Müssen Nutzende der Apps Einstellungen auf ihren Smartphones verändern?
Was passiert beim Scan der QR-Codes durch die Corona-Warn-App?
Wie unterscheiden sich die Corona-Warn-App und luca-App beim Check-in/der Eventregistrierung noch?
Warum wurde die Mitnutzung umgesetzt?
Warum kommt die Mitnutzung der luca-QR-Codes jetzt?
Sind die Daten der Nutzenden der Corona-Warn-App weiterhin sicher?
Welche Daten werden von der CWA an luca übertragen?
Braucht man nur noch eine App für die Eventregistrierung?
Müssen Nutzende beide Apps installieren, damit es funktioniert?

- remove all articles and redirect them to article
**Can the Corona-Warn-App read and process the QR codes from luca?**
- text update/change
  - **DE**
"Aktualisiert am 14. April 2022"
 "Die Eventregistrierung (Check-In-Funktionalität) der luca-app ist seit dem Frühjahr 2022 vorerst nicht mehr möglich. Daher können mit der Corona-Warn-App auch keine luca-Qr-Codes mehr gescannt werden."
  - **EN**
 "Updated April 14th, 2022"
 "The event registration (check-in functionality) of the luca app is no longer possible for the time being since spring 2022. Therefore, luca QR codes can no longer be scanned with the Corona-Warn-App."
  - in these articles:
    - ...

**Comment by Ein-Tim** [comment]
@dsarkar I could offer a PR for this, but if @MikeMcC399 wants to do this or things the Open-Source team should tackle this, that's also OK for me!

**Comment by dsarkar** [comment]
@Ein-Tim ok, great, very much appreciated.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Okay, sounds good!

**Comment by floscher** [comment]
Is the decision to immediately disable scanning luca codes with the CWA already final?

AFAIK the CWA is not relying on the luca app being active and the QR codes are probably still deployed in many locations.

So I would propose to delay the disabling of this feature, at least for now. Maybe it could even promote the CWA check-in in some cases, when people see that CWA users can still check-in with luca codes, but luca users can't anymore.

**Comment by Ein-Tim** [comment]
@floscher I didn't understand @dsarkar's answer in this way. I don't think scanning luca codes with CWA will be disabled, can you confirm @dsarkar?

**Comment by floscher** [comment]
@Ein-Tim I was referring mainly to the last bullet points:
> … 
> - text update/change
>   - **DE**
> "Aktualisiert am 14. April 2022"
>  "Die Eventregistrierung (Check-In-Funktionalität) der luca-app ist seit dem Frühjahr 2022 vorerst nicht mehr möglich. Daher können mit der Corona-Warn-App auch keine luca-Qr-Codes mehr gescannt werden."
>   - **EN**
>  "Updated April 14th, 2022"
>  "The event registration (check-in functionality) of the luca app is no longer possible for the time being since spring 2022. Therefore, luca QR codes can no longer be scanned with the Corona-Warn-App."
>  …

**Comment by Ein-Tim** [comment]
@floscher Yep, I know. We would need feedback from @dsarkar here, whether the luca compatibility will actually be removed or if it will stay possible to check in with CWA scanning luca QR codes. In later case, I would change the wording a bit.

**Comment by Ein-Tim** [comment]
PR #2757 provided, in Draft status until feedback reg. CWA & luca compatibility is given.

**Comment by MikeMcC399** [comment]
According to https://github.com/corona-warn-app/cwa-documentation/blob/main/event_registration.md#qr-code-compatibility-with-other-contract-tracing-apps-in-germany

"Representatives of other contact tracing apps may request allowlisting from the Robert Koch Institute through e-mail [CoronaWarnApp@rki.de](mailto:CoronaWarnApp@rki.de)."

so presumably at some stage, representatives of the luca app contacted RKI to request allowlisting and the request was granted. Were there any contractual agreements made at this time between luca and RKI, such as the right to cancel by either parties, or was it an informal process?

**Comment by MikeMcC399** [comment]
Whatever the outcome of this question:

- CWA continues to support scanning luca QR codes
- CWA stops supporting scanning luca QR codes

it is probably necessary for RKI to make a decision and make a statement. There seems to be too much guesswork going on here.

**Comment by dsarkar** [comment]
@floscher @MikeMcC399 @Ein-Tim Thanks for comments, stand by, please, we are waiting for info on this issue.

**Comment by floscher** [comment]
@dsarkar That this is the case from a technical standpoint was pretty much clear already, since this feature was built with independence in mind from the start.

The question was more, if there were plans to make changes to CWA to turn off the compatibility (I guess that's not the case, :+1: good) and if there were any contractual obligations. Also if there is any agreement with nexenio/culture4life that QR codes that are generated in the future continue to be compatible.

**Comment by Ein-Tim** [comment]
@dsarkar 

The real question is if it is planned to shut off the possibility to check in with CWA via luca QR codes.

**Comment by dsarkar** [comment]
My current understand is that existing luca qr codes at, for example, restaurants, bars, shops, will work within the CWA environment, independently of the luca app ant its infrastructure. No plan currently to block these qr codes. The luca qr codes still will work (scanning/check-in/contact tracing) for the foreseen future within the CWA environment.

**Comment by MikeMcC399** [comment]
@dsarkar 

Based on your understanding there are two FAQ articles in the https://www.coronawarn.app/en/faq/results/#check_in_luca section which are candidates for change:

The first is just outdated and now irrelevant:

![image](https://user-images.githubusercontent.com/66998419/165938188-12ff54ba-d144-47ee-9a28-0c520082c385.png)

and the second refers to a functionality in the luca app which apparently is no longer on offer:

![image](https://user-images.githubusercontent.com/66998419/165938375-087f8d41-98af-47b4-9b18-aba096bd99b0.png)

**Comment by MikeMcC399** [comment]
@dsarkar 

Are you still recommending the radical changes to the FAQs which you listed in https://github.com/corona-warn-app/cwa-website/issues/2751#issuecomment-1099174198?

If there hasn't been any particular new agreement between RKI and the luca app publishers I would tend to make only the changes which are absolutely necessary. If the luca codes can still be used in CWA then most of the articles can stay as they are.

**Comment by Ein-Tim** [comment]
@dsarkar 

Please, could you give us an update how you plan to proceed here?

**Comment by Ein-Tim** [comment]
Dear Open-Source-Team (@dsarkar / @larswmh),

could you please let us know how you plan to proceed here! I would like to keep my PR (#2757) in sync with the current status without having to resolve many merge conflicts. 
If there won't be an update on this anytime soon, I would like to close my PR. 

Please, give us a little update!

Thanks
Tim

**Comment by MikeMcC399** [comment]
There seems to have been no progress made on this issue. luca isn't doing contact tracing any more (see [their announcement](https://www.luca-app.de/luca-digitale-plattform-fuer-buergerinnen/) from Apr 5, 2022) and the CWA FAQs regarding luca are outdated.

**Comment by MikeMcC399** [comment]
@dsarkar 

Is there going to be any decision about how to describe the luca integration in the FAQs?

Three months ago you suggested removing all the luca articles.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Yes, the articles will be updated. We are waiting for feedback.
