### ISSUE TITLE
Missing description of RootBeer in DSFA

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2823]
## Where to find the issue

[Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf)

## Describe the issue

The "Bericht zur Datenschutz-Folgenabschätzung für die Corona-Warn-App der Bundesrepublik Deutschland, Öffentliche Version, Version 1.20, 09.12.2021" (DSFA) published on the website https://www.coronawarn.app does not discuss the use of the RootBeer security check in CWA for Android, so it is unclear what the goals of its use are.

Currently this topic is only touched on in the annexes of the document:

- https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung-anlage3.pdf Zeilen-Nr. 43 '[Release 2.12] Fehlinterpretationen von Sicherheitshinweis "Gerootetes Gerät" in der CWA-App'
- https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung-anlage8.pdf Zeilen-Nr. 75 "Fehlende/ unzureichende Löschung der Daten bei "In-AppReset" (nur Android)"

The use of RootBeer was introduced into the CWA Android app in Version 2.12 (see PR https://github.com/corona-warn-app/cwa-app-android/pull/4144). In Version 2.16 the notification was modified so that it can be suppressed until the next update of the app (see https://github.com/corona-warn-app/cwa-app-android/pull/4550).

## Suggested change

Add a description to the DSFA which explains the use of RootBeer in the CWA Android app. What additional data protection does RootBeer provide to CWA on Android? What risks are intended to be mitigated?

## References

- https://www.coronawarn.app/en/faq/results/#root_detection_android "[Google/Android]: Why do I receive a notification regarding administrator permissions (root permissions)?"

- https://github.com/scottyab/rootbeer RootBeer checker library

---
Internal Tracking ID: [EXPOSUREAPP-12983](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12983)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12983](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12983)

---
Corona-Warn-App Open Source Team

**Comment by GisoSchroederSAP** [comment]
Renewed request at the lawers office about date of release for the updated DSFA

**Comment by MikeMcC399** [comment]
This topic is **not** resolved by PR https://github.com/corona-warn-app/cwa-website/pull/3268 which publishes Version 2.00 of the DSFA. There is no mention of RootBeer in the PDF for Version 2.00 which is pending release.

**Comment by GisoSchroederSAP** [comment]
Okay, I did some research to better understand die current situation. Maybe, still I miss the intention of this issue here.

The legal discussions with solution architects involved did a risk assessment on the CWA messages that may occur on rooted devices (described in the appendix 3 mentioned above). Boths risks 

- the user might be confused and might feel unsave, uncomfortable... when receiving a message that he/she uses a rooted device
- the user might feel save having a "not-rooted" device, even if the library could not detect that the device was rooted.

For both scenarios the risk was evaluated and for "mitigation" the open communication within the FAQ agreed. Furthermore, based on the latest discussion, the remaining risk for users is accepted.

Our internal reserach of multiple ten-thousands of emails and store reviews also confirmed, this topic is not at all a high risk.

So, no further action is done, unless we receive evidence of an unknown risk here.
