### ISSUE TITLE
App availability information badge does not disappear

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2829]
## Where to find the issue

- https://coronawarn.app/de
- https://coronawarn.app/en

## Describe the issue

The badge which informs that the app is available and can be downloaded from the App & Play Store does not disappear anymore.

Here's a video:

https://user-images.githubusercontent.com/67682506/166635970-786e0763-d354-4b66-b072-543889728aaf.MOV

## Suggested change

I remember that the badge disappeared in earlier versions of the website & suggest to restore this behavior.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- This was changed by https://github.com/corona-warn-app/cwa-website/pull/2483 which has an accessibility label.

- You can dismiss the download info by tapping on the "X".

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Okay, thanks! I can only imagine how this influences a11y, maybe because the content is dynamically changing? 
Maybe the author of the PR (@larswhm) could comment here and clarify?

**Comment by larswmh** [comment]
Hey @Ein-Tim, as @MikeMcC399 already pointed out this change was made due to accessibility recommendations. 

During the internal accessibility test it was emphasized, among other things, that no change of context should take place when focusing on an element. This can lead to cognitively impaired users having to reorient themselves and additionally navigate in order to continue their task. That is why the element can now only be closed by a targeted user interaction. The automatic reappearance should also not take place, since the download options are mentioned at the bottom of the page anyway.

**Comment by Ein-Tim** [comment]
Thanks @larswmh! Closing this issue.
