### ISSUE TITLE
Multiple website issues

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2870]
## Where to find the issue

https://www.coronawarn.app/en/
https://www.coronawarn.app/en/blog/
https://www.coronawarn.app/en/analysis/
https://www.coronawarn.app/en/faq/
https://www.coronawarn.app/en/faq/results/

## Describe the issue

Multiple issues are currently occurring on the CWA website

1. https://www.coronawarn.app/en/ menu button does not work in narrow mode, 
2. https://www.coronawarn.app/en/blog/ the new blog search does not work
3. https://www.coronawarn.app/en/analysis/ no graphs are shown
4. https://www.coronawarn.app/en/faq/ search does not work
5. https://www.coronawarn.app/en/faq/ legacy links do not work
6. https://www.coronawarn.app/en/faq/results/ search does not work
7. https://www.coronawarn.app/en/faq/results/ duplicate articles are not shown

**Comment by MikeMcC399** [comment]
Sorry for "pre-release" of this issue! I accidently hit the Return button whilst I was still composing the issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting, we are having a look at the issues. See https://github.com/corona-warn-app/cwa-website/pull/2871

**Comment by Ein-Tim** [comment]
I just retested and all reported issues still occur. Please reopen the issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Fixed.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Fixed

I checked each item and I agree that the issues are resolved. Thank you!

**Comment by svengabr** [comment]
The problem was related to s3cmd v2.0 which is the latest version available to ubuntu-latest.

There is a bug in guessing mime types and it caused all assets like css/js to be uploaded with `content-type` `text/plain`. Due to our content security policy, the script can only be executed with `text/javascript`.

Related issue:
https://github.com/s3tools/s3cmd/issues/643 

The bug is fixed in s3cmd >= 2.2
