### ISSUE TITLE
Remove hack from #296

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-website#297]
## Where to find the issue
/src/pages/{de|en}/faq/(39508).html

## Describe the issue
These files should be removed as soon as the issue in the Android app is fixed and correct links are presented in the error message. They were introduced in #296 to avoid showing a 404 to end users of the app but lead them to the correct faq entry.

## Suggested change
Remove the files!

**Comment by tkowark** [comment]
Other stuff to remove:

* This workflow step: https://github.com/corona-warn-app/cwa-website/blob/601cda93f1f3b9d3ed9949b28c352c468ae3f87d/.github/workflows/deploy-master.yml#L49
* This gulp function: https://github.com/corona-warn-app/cwa-website/blob/601cda93f1f3b9d3ed9949b28c352c468ae3f87d/gulpfile.js#L288

**Comment by heinezen** [comment]
Is the app fixed?

**Comment by MikeMcC399** [comment]
@heinezen 
> Is the app fixed?

AFAIK: Yes. However I would consider just leaving these small redirect files where they are, since they are not doing any harm.

As far as the links displayed after error 39508 are concerned, they went through a revision history in the following order:

Link | Example Screenshot
--- | ---
https:://www.coronawarn.app/de/faq/(39508) | https://github.com/corona-warn-app/cwa-app-android/issues/774#issuecomment-675382478
https:://www.coronawarn.app/de/faq/ (39508) | https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-691315839
https:://www.coronawarn.app/de/faq/#39508 | https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-727540097

In the second one in the list there was a space before the "(" so that link didn't work at all as intended.

**Comment by Ein-Tim** [comment]
Any update if the redirect will stay or if you will remove them?

**Comment by Ein-Tim** [comment]
Maybe @tkowark could real quick comment why he thinks that the redirect should be removed?

**Comment by tkowark** [comment]
For me it was just a quick hack to work around an error within the app. For the sake of a clean code base, I usually try to get rid of such stuff rather sooner than later. And especially the Mime Type rewriting in the GitHub Action looked like it could become troublesome one day.

That being said, it can also stay in as it really is just a rather small change.
