### ISSUE TITLE
iOS: Layout issue when using the blog search on mobile devices

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#2990]
## Where to find the issue
- https://www.coronawarn.app/en/blog/
- https://www.coronawarn.app/de/blog/

## Describe the issue
Using the blog search on my iPhone XR, the page zooms in to the search field, however, this is not a good thing to do, as the page then cuts of some content. See this video:

https://user-images.githubusercontent.com/67682506/176706022-728f4079-c39e-4a33-a306-a7f9d8fb09f9.MP4

## Suggested change
Do not zoom in to the search field at all OR align the search to the one on https://www.coronawarn.app/de/faq.

---
Internal Tracking ID: [EXPOSUREAPP-13502](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13502)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Which browser are you using?

I did not see the problem with Google Chrome emulating an iPhone XR.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'm using Safari for iOS. When you tried to emulate, was the software keyboard shown? I think this is what causes the website to zoom in.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> When you tried to emulate, was the software keyboard shown? 
No, I did not use a software keyboard. I emulated under Windows 11 using the hardware keyboard.

I expect that your software keyboard comes from iOS, not from the Safari for iOS browser.  

I also tried Google Chrome on Android where there is no issue either. Do you have the ability to test with Google Chrome on iOS?

This issue is discussed in https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> I expect that your software keyboard comes from iOS, not from the Safari for iOS browser.

Yes, that's correct.

> Do you have the ability to test with Google Chrome on iOS?

I will try.

> On your video it did not seem to prevent you using the blog search function.

No, but it zoomed into the page so that it made the blog post teasers cut off.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This seems to be an issue with iOS. Apart from
https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone which I also mentioned, there is another article 
https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/ I found that describes the issue.

Does the screen zoom back out again after you have entered your search term?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
>> Does the screen zoom back out again after you have entered your search term?
>
> No, this has to be done manually. This is not a good experience for the user.

I agree that this is not good.

Since it only seems to affect iOS devices I don't have the means to both make changes and test them. Perhaps you could try out if one of the methods from the links in https://github.com/corona-warn-app/cwa-website/issues/2990#issuecomment-1172023968 works for you? Otherwise the issue needs to be picked up by a web developer.

Also maybe add iOS to the title of this issue if you also think that the issue only happens on iOS?

**Comment by Ein-Tim** [comment]
@MikeMcC399 As you can see I changed the title. Reg. the methods you linked to, I weren't able to test them successful, so I guess it would be best if this issue is picked up by the team.

Have a nice Sunday!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting. PR was merged just now.

**Comment by Ein-Tim** [comment]
Closing as fixed. Thanks to @brifemu!
