### ISSUE TITLE
TAN procedure FAQ

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3063]
## Where to find the issue

- https://www.coronawarn.app/en/faq/results/#tan_procedure "TAN Procedure"
- https://www.coronawarn.app/de/faq/results/#tan_procedure "TAN-Verfahren"

## Describe the issue

There are multiple issues and inconsistencies with the [TAN Procedure](https://www.coronawarn.app/en/faq/results/#tan_procedure) FAQ added through PR https://github.com/corona-warn-app/cwa-website/pull/3060 on July 29, 2022.

Inconsistencies with other usage:

1. The virus name is written inconsistently as "Sars-CoV-2", differing from accepted capitalization.
2. The hotline telephone numbers are formatted as `0800-7540002` and `+49.30.49875402` differing from renderings of the phone number in other places in the FAQ and in the footer of the website.
3. The main page of the app is referred to as "the Home Screen" differing from almost all other FAQ articles which refer to the "Status tab" instead.
4. The English instructions contain the wrong text "Are you getting tested?" / "Next" / "Your PCR test was positive?" which are literal translations of the German app text, and not the text which is actually used by the app.
5. The app name is inconsistently rendered as "Corona Warn App" (missing hyphens) and "Corona alert app" in the English text.

Other points:

- In German there is a missing space in the abbreviation `z.B.` (see issue https://github.com/corona-warn-app/cwa-website/issues/1689 and [DIN 5008](https://de.wikipedia.org/wiki/DIN_5008#Abk%C3%BCrzungen_(Abschnitt_4.5))).
- The English translation has some grammar issues.
- Typos in both language versions.
- Missing punctuation marks.

## Suggestion

1. Write the virus as "SARS-CoV-2" to be consistent with other places on the website and with [RKI: COVID-19 (Coronavirus SARS-CoV-2)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV_node.html).
2. Write the hotline telephone number as `0800 7540002` and `+49 30 498 75402`.
3. Use the term "Status" to refer to the app "Home Screen".
4. Correct the tile texts to read "Manage Your Tests" / "Continue" / "Was your PCR test positive?".
6. Correct typos and punctuation.
7. Improve English translation.
8. Refer to app consistently as either Corona-Warn-App or CWA.

**Comment by MikeMcC399** [comment]
I will submit a PR to resolve this issue next week.

**Comment by Ein-Tim** [comment]
Hi @MikeMcC399,

thanks for this issue! Could you please add to the list (and fix with your PR) that the entry includes the following sentence:
"To reasonably record encounters through contact tracing and alert these contacts, the **Corona alert app** must be installed on the smartphone for at least a period of time; the TAN hotline will verify that period.", which uses Corona alert app instead of Corona-Warn-App.

Thanks for opening this issue, I support your request to leave PRs open for a longer period of time, I only reviewed the PR content-wise, but I have to admit that at least some of the issues you now spotted & the wrong translation "Corona alert app" should have been spotted by me in my review. Sorry for missing them!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Good catch for the app name. I will add that to the list of issues and correct it.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-website/pull/3067 submitted.

**Comment by christianneu** [comment]
As already mentioned in PR #3067, the fix looks good so we can merge it. Therefore I would close the issue. Thanks for the changes.
