### ISSUE TITLE
Repository and website maintenance

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3103]
@GisoSchroederSAP 

I remember you writing a few weeks ago that the website would continue to be maintained. There are now PRs waiting from up to three weeks ago and issues from two months ago awaiting attention. The last commit to the repository is now 13 days ago.

Will the Open Source Team become regularly active again here soon?

**Comment by Ein-Tim** [comment]
To be honest slowly it get's really depressing in the CWA repositories! While the developers (especially @mtwalli) do a really great job in the last days, they can and should not replace a community management team. I really hope the community managers come back soon, also to get work on the website done!

**Comment by MikeMcC399** [comment]
I withdraw the question. No answer is also an answer 🙁

**Comment by GisoSchroederSAP** [comment]
Yes, the website will continue to be maintained. 
Yes, in the current situation of limited capacity and limited movement in political and social discussions - all these tasks and  activities take significant longer time to be performed, sorry for that. 
We still have an eye on the pull requests, but we also have to prioritize at least the tasks
- for the website, 
- for the app release preparation, 
- for the app documentation parts, 
- for the reporting tasks, 
- for the app stores, 
- for the mailbox and as well 
- for the alignment with our industry partners.  

I understand, you are not satisfied with our current performance, and so aren't we. These seem to be the late affects of the "summer lull", in which also Community Management capacities were dramatically reduced because the pandemic supposedly did not require any further investment or attention. Sorry guys, we try to keep the ball rolling...

**Comment by MikeMcC399** [comment]
@GisoSchroederSAP 

You confirmed what we already saw for the last two months: that tasks will take a significantly longer time. I don't expect to be submitting any new PRs in that case, unless the situation changes.
