### ISSUE TITLE
Extend `further_details` FAQ entry with information on where to find more details reg. vaccination statistics

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3164]
## Enhancement description

- Add "The [COVID-19 vaccination dashboard](https://impfdashboard.de/en/) provides further detailed information about vaccination statistics" to the section on https://coronawarn.app/en/faq/results/#further_details which lists vaccinations

- Add "Unter dem [COVID-19 Impfdashboard](https://impfdashboard.de/) finden Sie weitere Details zu den Impfstatistiken" to https://www.coronawarn.app/de/faq/results/#further_details

(Wording by @MikeMcC399, https://github.com/corona-warn-app/cwa-documentation/issues/922#issuecomment-1288068127)

## Problem and motivation
The CWA includes the following statistics, among others, on vaccination:

- "People Who Have Received at Least One Vaccine Dose" ("Mindestens eimal geimpfte Personen")
- "People Who Have Basic Immunization" ("Grundimmunisiert")
- "People Who Have Received a Booster Vaccination" ("Personen mit Auffrischimpfung")

The used terms are nowhere defined in the app. For example, the user can't tell if "People Who Have Basic Immunization" includes all people who have received two shots or three. It would therefore be good to add a link to the [COVID-19 vaccination dashboard](https://impfdashboard.de/en/), where these terms are defined, to the FAQ entry https://www.coronawarn.app/en/faq/results/#further_details & https://www.coronawarn.app/de/faq/results/#further_details.

## Is this something you're interested in working on
Yes, but I will only have time for it in ca. 7 days. If you want to get this done faster, please do it yourself!

## Additional information
This is a follow-up to https://github.com/corona-warn-app/cwa-documentation/issues/922

---
Internal Tracking ID: [EXPOSUREAPP-14219](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14219)

**Comment by larswmh** [comment]
Hi @Ein-Tim, are you still interested in working on this? We think this would be a suitable addition for the FAQ article.

---
Corona-Warn-App Open Source Team

**Comment by brianebeling** [comment]
Thank you Tim, that'd be great. Don't hesitate letting us know if that is something you can't work on, if something gets in your way, so we can take care of it. I'll most likely also be available on the weekend some time.

**Comment by MikeMcC399** [comment]
I may be missing something, but it seems that this issue has become obsolete due to PR https://github.com/corona-warn-app/cwa-website/pull/3179

This PR defined [basic](https://www.coronawarn.app/en/faq/results/#glossary_basic_immunization) and [booster](https://www.coronawarn.app/en/faq/results/#glossary_booster_vaccination) vaccinations in the Glossary and linked the FAQ article https://www.coronawarn.app/en/faq/results/#further_details to the Glossary.

My suggestions, that were quoted in the original post, are from a time before PR #3179.

https://www.coronawarn.app/en/faq/results/#further_details

![image](https://user-images.githubusercontent.com/66998419/207873676-da1d3c99-1e3a-48c0-a039-624d9919d5b9.png)

https://www.coronawarn.app/en/faq/results/#glossary_basic_immunization

![image](https://user-images.githubusercontent.com/66998419/207873793-e0fdb8ed-e170-497a-8bea-d1629dcd9a94.png)

https://www.coronawarn.app/en/faq/results/#glossary_booster_vaccination

![image](https://user-images.githubusercontent.com/66998419/207874270-f8b65a1c-6348-4dc7-b5a5-b1c1db79c899.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'm very short on time today & tomorrow, I hope it's ok for you if I check on the weekend?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

No pressure from me! Please take your time.

**Comment by Ein-Tim** [comment]
I'd agree with @MikeMcC399 that this issue is obsolete. @brianebeling could you have another look, please?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest to close the issue now. It was based on my suggestion, which no longer applies, and you have agreed to that.

@brianebeling and @larswmh may like to also respond, however I can't imagine any other outcome, apart from saying that the issue was already addressed and that no further FAQ changes are needed.

**Comment by brianebeling** [comment]
See above, thank you nonetheless. It flew right over my head that we already submitted a PR for this.
