### ISSUE TITLE
Add new terms reg. vaccination statistics to the Glossary

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3165]
## Enhancement description
Please add the definitions of the following terms (and their German equivalents listed in brackets) to the [Glossary](https://www.coronawarn.app/en/faq/results/?search=&topic=glossary):
- "People Who Have Received at Least One Vaccine Dose" ("Mindestens eimal geimpfte Personen")
- "People Who Have Basic Immunization" ("Grundimmunisiert")
- "People Who Have Received a Booster Vaccination" ("Personen mit Auffrischimpfung")

## Problem and motivation
The app includes the above-mentioned terms without explaining them. It would be good to at least have a definition of the terms in the CWA website glossary. 

## Is this something you're interested in working on
No, this should be done by the team.

## Additional information
This is a follow-up to https://github.com/corona-warn-app/cwa-documentation/issues/922

---
Internal Tracking ID: [EXPOSUREAPP-14220](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14220)

**Comment by brianebeling** [comment]
Hey Tim, thanks for the feedback. We will take a look, sounds like a good idea.

**Comment by MikeMcC399** [comment]
If the terms from the statistics tiles:

- "Basic Immunization" / "Grundimmunisiert"
- "Booster Vaccination" / "Personen mit Auffrischimpfung"

are to be defined in the Glossary that would be a good improvement.

I don't think it is necessary to make a Glossary entry for the term "People Who Have Received at Least One Vaccination Dose" / "Mindestens einmal geimpfte Personen" since the general meaning is clear from the plain text label, even though in https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland#erkl%C3%A4rung-zum-merkmal-impfstatus there is a detailed description:

 "Die Gesamtzahl mindestens einmal Geimpfter (min1) umfasst alle Meldungen, für die in den Daten des DIM die Impfserie 1 angegeben ist. Als Impfserie 1 gelten Erstimpfungen mit den in Deutschland zugelassenen und verfügbaren Impfstoffen. Nicht enthalten sind Impfungen von Personen, die erstmalig in Deutschland geimpft wurden, zuvor aber von einer SARS-CoV-2 Infektion genesen sind oder bereits eine Impfung im Ausland erhalten hatten. Diese gelten direkt als grundimmunisiert."

Users who are interesting in the correct scientific use of the numbers would be better advised in any case to work directly with the [RKI GitHub repository: COVID-19-Impfungen in Deutschland](https://github.com/robert-koch-institut/COVID-19-Impfungen_in_Deutschland) instead of using the statistics tiles which are more for general information.

**Comment by brianebeling** [comment]
Quick heads up, I'm working on this
