### ISSUE TITLE
Distinction between PCR-test types

### ISSUE THREAD

**Issue by bloodmandarin** [corona-warn-app/cwa-website#3294]
As the designers intended it, I was trying to use the positive PCR-result that I received yesterday, to inform my network of my diagnosis. 

Only to find out that there is a distinction between different types of PCR-Tests and that only specific ones are legitimate foundations for a "positive"-status via the app. 

It was incredibly frustrating that not only a) there was no mentioning whatsoever in the app that I required a particular type of PCR, much less/but also that b) the test station location tools make no mention of different types of PCR-tests. 

So now I neither know what type of PCR-test I need to register my diagnosis, nor do I know where I can get it...

---
Internal Tracking ID: [EXPOSUREAPP-13453](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13453)

**Comment by MikeMcC399** [comment]
@bloodmandarin 

I'm sorry to hear about your bad experience. What type of PCR test did you take?

There are already issues open on this topic. I just want to make sure that I point you in the right direction.

**Comment by MikeMcC399** [comment]
@bloodmandarin 

Assuming you took a Rapid PCR Test, then the current FAQ articles to look at are:

- https://www.coronawarn.app/en/faq/results/#glossary_rapid_pcr_test

- https://www.coronawarn.app/en/faq/results/#rat_tan_hotline

It was also announced on https://twitter.com/BMG_Bund/status/1601146184537583617 that CWA version 3.0 will allow users to notify others of a positive test independently of the type of test. They say that the release date is planned for Jan 18, 2023.

**Comment by MikeMcC399** [comment]
@bloodmandarin 

I'm still assuming that you took a Rapid PCR Test, in this case your points 

>It was incredibly frustrating that not only a) there was no mentioning whatsoever in the app that I required a particular type of PCR, much less/but also that 

are covered in:

- https://github.com/corona-warn-app/cwa-documentation/issues/902

> b) the test station location tools make no mention of different types of PCR-tests.

and in

- https://github.com/corona-warn-app/cwa-map-public-frontend/issues/8

both of which were raised several months ago. I doubt that much will change before the CWA 3.0 release, but thank you for highlighting the issue, so that the appropriate people are made aware.

**Comment by MikeMcC399** [comment]
Is there anything in this issue which is not already covered in other issues or in the FAQs?

**Comment by larswmh** [comment]
As suggested, I will close this issue now due to inactivity by @bloodmandarin. Your report has been attached to an internal ticket that was already created for a very similar issue, which has been mentioned in previous comments here. Looking forward to future changes in the app, it is unfortunately unlikely that this will be changed.

Thank you for providing extensive help on this issue @MikeMcC399.
