### ISSUE TITLE
Publish the newest version of the DSFAS

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3330]
## Where to find the issue
- https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf

## Describe the issue
The currently published document is from October 2022 and there are multiple outdated statements in it now, as version 3.0 enables users to warn others without having to scan a QR code or enter a TAN. Also, it describes the hotline process, which is shut down on 31. Jan 2023.

## Suggested change
Please publish the newest version of the DSFAS. The newest version should describe the influence of version 3.0 on the security architecture of the CWA. 

---
Internal Tracking ID: [EXPOSUREAPP-14646](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14646)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. This issue has been forwarded internally.

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@Ein-Tim 

According to the new [Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) valid from May 1, 2023 there is no longer any personal data storage.

It might be interesting from a historical point of view to see the [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf) which was valid on April 30, 2023, however since no action has been taken on your issue from January I would be quite surprised if suddenly RKI decided to publish any update, if they have one. In terms of DSFA from May 1, 2023 onwards, I don't see any impact apart from the fact that the app stores record who has downloaded the app.

**Comment by Ein-Tim** [comment]
I raised this topic internally and will follow-up then.
