### ISSUE TITLE
Dashboard: Explanation for Label "TestV adjustments" needed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#3451]
## Where to find the issue
- https://www.coronawarn.app/en/analysis/
- https://www.coronawarn.app/de/analysis/ 

## Describe the issue
The label "TestV adjustments" / "TestV Anpassungen" is not self-explanatory and, in my opinion, needs an explanation. 

## Suggested change
At least: Add a FAQ entry on the TestV changes form 01.03.2023 so that users can head over to the FAQs from the dashboard page
Best: Explain the change in an info box which, i.e., pops up when the label is clicked.

---
Internal Tracking ID: [EXPOSUREAPP-14999](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14999)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- This circles back to issue https://github.com/corona-warn-app/cwa-website/issues/3415 which I closed since there was no resulting action to document the external legal change to TestV with its organisational impact. The app and infrastructure was not changed, only the testing ecosystem.
- See https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html for German explanation

**Comment by Ein-Tim** [comment]
Thank you @larswmh & @dsarkar!
