### ISSUE TITLE
Obsolete Event QR-Code

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#3484]
CWA can no longer scan QR codes, so the Event QR-Code is now obsolete.

It has a prominent position in the header

![image](https://user-images.githubusercontent.com/66998419/235689518-1e1e5a1d-1d2d-43e9-ac91-a86ef7853c46.png)

so it should be removed from there.

On https://www.coronawarn.app/en/eventregistration/ there should at least be a note that it is no longer applicable, if the page itself is still retained. If the page is removed, then the Cypress tests would also need to be changed.

---
Internal Tracking ID: [EXPOSUREAPP-15169](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15169)

**Comment by Ein-Tim** [comment]
Hi Mike, 

thank you for raising this issue! We will see how we best handle this, just an idea that popped up in my head while I was writing this: Adding a disclaimer to the page & deactivating the input fields and buttons, so that no new QR codes can be created. But as said, this is just one way how we could possibly handle this.
In general, the team agreed that we don't want to remove any pages. 
The idea is to keep the content of the website available, maybe archive some (for example the FAQ entries by changing the structure, or removing some of the screenshot pages), but it was important to us that everyone can still see and access most of the features and information the website once offered.

Our internal work on this, however, is not yet finished, and we will take all of your feedback into consideration!

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-website/pull/3492

**Comment by MikeMcC399** [comment]
@dsarkar 

- Do you plan to remove "Event QR-Code" from the header or do you want to close this issue now that #3492 has been merged?

**Comment by dsarkar** [comment]
@MikeMcC399 We will keep "Event QR-Code" in the header.

**Comment by MikeMcC399** [comment]
@dsarkar 

> We will keep "Event QR-Code" in the header.

Thanks. So I will close, since at least part of the suggestion has been implemented and there is no further action planned.
