### ISSUE TITLE
Optimize wording of FAQ "What do the exposure check logs show?"

### ISSUE THREAD

**Issue by NKarolak** [corona-warn-app/cwa-website#422]
* Website URL Path: https://www.coronawarn.app/en/faq/#keys_matches
* Line / Paragraph:
* Question:

It is a common misunderstanding - at least for German speaking users - to assume that the number below the "Exposure checks" is _the number of people you met the past 14 days_.
![grafik](https://user-images.githubusercontent.com/34504100/94995041-cbab4100-059b-11eb-9611-26dff3d9adac.png)
See e.g. [Twitter](https://twitter.com/diese_Sirene/status/1312300798517284864?s=20)

I am assuming - please correct me! - that the wording on that page is created by Google, thus out of direct reach for us.
Even if so, we could still improve **FAQ entry [What do the exposure check logs show](https://www.coronawarn.app/en/faq/#keys_matches)**. Do you agree on the following?

![grafik](https://user-images.githubusercontent.com/34504100/94995002-86870f00-059b-11eb-9ce6-31fb19ba1568.png)

1) Introduction

> The exposure check logs show how many keys that report a positive test result are downloaded from the server, and how many of them are matching the keys that your phone has collected. For infos about the app flow, see How do you get information about a risk of infection? for details.

Well, no. The number on the "landing page" is only the number of the "check packages". Each package contains thousands of keys and does not indicate any number of people involved since each person is represented by multiple keys. It must be stated that the number on the landing page does not tell anything about the number of people someone has met.

2) Missing hint how to reach the following captions
It should be mentioned, that tapping on "Exposure checks" will open the exposure log, were you can inspect each package.

**Comment by Ein-Tim** [comment]
> I am assuming - please correct me! - that the wording on that page is created by Google, thus out of direct reach for us.

Your assumption is correct. 

> Missing hint how to reach the following captions
It should be mentioned, that tapping on "Exposure checks" will open the exposure log, were you can inspect each package.

This would surely nice to be included, the question is if this is on every Android Version, which supports ENF the same or if this behavior is different on different versions (cc @daimpi).

**Comment by daimpi** [comment]
>  1. Introduction
> 
> 
> > The exposure check logs show how many keys that report a positive test result are downloaded from the server, and how many of them are matching the keys that your phone has collected. For infos about the app flow, see How do you get information about a risk of infection? for details.
> 
> Well, no. The number on the "landing page" is only the number of the "check packages". Each package contains thousands of keys and does not indicate any number of people involved since each person is represented by multiple keys.

Just so everyone is on the same page what we're talking about here, the number on the landing page looks like this in Android (btw. @Ein-Tim is there a similar number in iOS?):
<img src="https://user-images.githubusercontent.com/22129968/94008971-15c64280-fda4-11ea-878a-9e721a28b9b2.png" width="400">

Tbh: I don't think the introduction of this FAQ entry refers to this number, but rather tries to make a more general statement what kind of information can be found in the EN log. 

The meaning of this number is described in the "Exposure checks" section of this FAQ entry, which makes sense given that this number is found right where it says "Exposure checks":
> For each day, there is an entry for each of the last 14 days, see My exposure log shows multiple, simultaneous checks for exposures.

Although I've to admit that this description is also not entirely clear. It would be easier to understand if it could explicitly say something about this number like "therefore your log will contain 14x14=196 checks". But unfortunately this will almost never be true because
1. Google actually shows/counts checks performed for more than the past 14 days 
2. even if they only counted the past 14 days there will be quite some ppl for whom this number is higher/lower b/c of issues like API 39508 and failing background checks.

> It is a common misunderstanding - at least for German speaking users - to assume that the number below the "Exposure checks" is the number of people you met the past 14 days. 
> […]
>  It must be stated that the number on the landing page does not tell anything about the number of people someone has met.

I agree with this idea. I've also encountered a fair share of ppl who mistook this number for the number of ppl they met over the past 14 days. In such cases I usually tell them that this information cannot be known by CWA or ENF because the pipeline was designed with "privacy by design" in mind and link them to my summary [here](https://github.com/corona-warn-app/cwa-wishlist/issues/124#issuecomment-660121125). 

Maybe a sentence could be added to the "Exposure checks" section of the FAQ entry? Something along the lines of "Note: the number shown here is in no way related to the number of people you met over the last 14 days."? What do you think?


> > Missing hint how to reach the following captions
> > It should be mentioned, that tapping on "Exposure checks" will open the exposure log, were you can inspect each package.
> 
> This would surely nice to be included, the question is if this is on every Android Version, which supports ENF, the same or if this behavior is different on different versions (cc @daimpi).

Yes I also agree that this would be a nice addition. And yes: afaik this looks the same for all Android devices running ENF.

**Comment by Ein-Tim** [comment]
> Just so everyone is on the same page what we're talking about here, the number on the "landing page" looks like this in Android with English language settings (btw. @Ein-Tim is there a similar number in iOS?)

No, there is nothing like this in iOS @daimpi (in the Versions >iOS 13.7 there was a number which showed how many new files were downloaded in the last 24 hours, but iOS 13.7 and above don't show this anymore)

**Comment by loki-cui** [comment]
Thanks for your comments. 
We also had a couple of users from the store community that raised the same question. So this is indeed something that needs a better explanation.

New wording is already in progress.

Best regards
Corona-Warn-App Open Source Team

**Comment by loki-cui** [comment]
As this will also be updated by Google soon, we will only add a short explanation and not change the complete FAQ-entry. 
https://www.coronawarn.app/de/faq/#keys_matches
https://www.coronawarn.app/en/faq/#keys_matches

Pls. replace the explanation in the yellow-highlighted section:

![image](https://user-images.githubusercontent.com/69584390/96226435-e6fe4f00-0f92-11eb-84fd-fa78019eadd6.png)

**DE**
Dieser Wert gibt nicht die Anzahl der Begegnungen wieder. Bitte klicken Sie eine Stufe weiter: Dort sind die Überprüfungen von bis zu 15 Tagen protokolliert (heute plus die letzten 14 Tage). Das Auswählen eines Eintrages führt zur Detailansicht mit den entsprechenden Zeitstempeln und der Anzahl der abgeglichenen Schlüssel. 

**EN**
This value does not reflect the number of encounters. Please tap one level further: This is where the checks of up to 15 days are logged (today plus the last 14 days). Selecting an entry leads to a detailed view with the corresponding time stamps and the number of matched keys.
