### ISSUE TITLE
Using iOS 14.2 leads to the following issues wirh the app:

### ISSUE THREAD

**Issue by marsp61** [corona-warn-app/cwa-website#485]
EN 2
EN 11
EN 13

It's not working since 16.10.2020 is there Beta of the which I could test? Or will be the upcoming update of the app solve the issue? Or can it be only solved on side of Apple?

## Your Question

* Website URL Path:
* Line / Paragraph:
* Question:

**Comment by heinezen** [comment]
Hey @marsp61 ,

The error you get is a well known issue which is already discussed in https://github.com/corona-warn-app/cwa-app-ios/issues/1339#issuecomment-710449367 Please check the discussion there for further information. It will be fixed in a later update as @Ein-Tim already pointed out. 

CH

---
Corona-Warn-App Open Source Team
