### ISSUE TITLE
FAQ on cwa web page references outdated cwa version

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-website#505]
## Where to find the issue

FAQ entry: [Hintergrund­aktualisierung](https://www.coronawarn.app/de/faq/#no_risk_update_ios14) , 
section "[Apple/iOS]: Mein Risikostatus wurde seit über einem Tag nicht mehr aktualisiert. Internet war aber verfügbar, was läuft hier falsch?"
on your web page.

## Describe the issue

> Sie sollten die App mindestens in Version 1.1.2 verwenden.

The recommendation is to update to the newest cwa version; however, the referenced version 1.1.2 is outdated. Currently the latest released version is 1.5

**Comment by Ein-Tim** [comment]
Hey @ndegendogo
I do not think this is a bug, because there is the word "mindestens", and this is true, you can use all App Versions since 1.1.2 to have reliable Background Checks. Before 1.1.2 they didn't work correctly so I would not change this

**Comment by ndegendogo** [comment]
> all App Versions since 1.1.2 to have reliable Background Checks

@Ein-Tim are you kidding? See [iOS#916](https://github.com/corona-warn-app/cwa-app-ios/issues/916#) and [iOS#1227](https://github.com/corona-warn-app/cwa-app-ios/issues/1227#)

Or do you say that reliability of background check was not improved since 1.1.2 (release on 24 July, and now it is 3 months later)?

If this is true, I am ... surprised

**Comment by Ein-Tim** [comment]
@ndegendogo 

Maybe reliable was the wrong word, better would be working 😅

I can only tell the "story" from my point of view:
With all versions before 1.1.2, Backgorund Checks just did not happen at all.
All Versions after 1.1.2, tbh, I did not notice any real change... Maybe some little things but no big improvements...

And I am also somebody who has the problem that the checks are not done in the promised 24h...

So or so, I would leave the FAQ how it is, because before this sentence:

>Sie sollten die App mindestens in Version 1.1.2 verwenden.

there is this sentence: 
Zuerst stellen Sie bitte sicher, dass die neuesten Versionen von iOS **und der App** installiert sind.

So this makes clear it would be the best to use the newest version but at least 1.1.2...

**Comment by ndegendogo** [comment]
@Ein-Tim and maybe you are right - the moment to update this FAQ entry should be **after** they found the root cause of the unreliabilities and addressed it properly ...

I'll continue to watch it with cwa 1.5.1 (1) or later ...

**Comment by svengabr** [comment]
I did change the wording as follows:
>Zuerst stellen Sie bitte sicher,  dass die neuesten Versionen von iOS und der App installiert sind. Die aktuellste iOS Version der Corona Warn App ist aktuell <b>[ios.current-app-version]</b>. Wenn eine niedrigere Version installiert ist, öffnen Sie den App Store, um herauszufinden, ob es Updates für die Corona-Warn-App gibt.

> First, please ensure that you are running the current version of iOS and the app. The latest version of the Corona Warn App is currently <b>[ios.current-app-version]</b>. If you are running a lower version, open the App Store to check if an update for Corona-Warn-App is available.
