### ISSUE TITLE
FAQ entry: path for exposure checks needs to be corrected

### ISSUE THREAD

**Issue by loki-cui** [corona-warn-app/cwa-website#618]
## Where to find the issue
https://www.coronawarn.app/de/faq/#exposure_check
https://www.coronawarn.app/en/faq/#exposure_check

## Describe the issue
The path to check the risk notificationsis more hidden and require one extra tap. 

## Suggested change
Pls. correct the path as follows:

**EN**
Settings - 'Exposure Notifications' - 'Exposure Logging Status' - 'Exposure Checks' 

**DE**
Einstellungen - 'Begegnungsmitteilungen' - 'Status von Begegnungsaufzeichnungen' - Begegnungsüberprüfungen

**Comment by MikeMcC399** [comment]
@loki-cui 
Are those instructions supposed to be for Android or for iOS?

https://www.coronawarn.app/en/faq/#exposure_check currently says:

"Your phone settings display the exposure checks for the last 14 days: Apple: 'COVID-19 Exposure Logging', Android: 'Exposure checks'. When the app was running constantly during the last two weeks, you should see 14 checks within the last 24 hours."

On Android the way to get to the exposure checks is:

Settings > Google > COVID-19 exposure notifications

You have written:
>EN
Settings - 'Exposure Notifications' - 'Exposure Logging Status' - 'Exposure Checks'

In any case this article needs updating because the statement:

"When the app was running constantly during the last two weeks, you should see 14 checks within the last 24 hours."

was no longer true for 1.6.x and is changing once again for 1.7.x.

There is another related open issue https://github.com/corona-warn-app/cwa-website/issues/578 "FAQ: Multiple exposure checks not currently accurate".

**Comment by Ein-Tim** [comment]
@MikeMcC399 These are the instructions for iOS (under iOS 13.7 and newer)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> These are the instructions for iOS (under iOS 13.7 and newer)

Good to know. Thanks!

For Android users the article doesn't describe the steps to get to the display which shows:
Exposure checks
16 checks in the past 14 days

It may be better to split this into two different articles: one for Android and another for iOS.

It probably needs a good review of all articles covering these and similar topics, making sure the facts are correct for the current versions of ENF / ENS and CWA iOS / CWA Android.

For instance the reference to the log limit on Android is not the complete story. I think Google didn't remove it completely, they just increased it (iirc to 300).

**Comment by heinezen** [comment]
Addressed in #645
