### ISSUE TITLE
Outdated FAQ entry reg. free download of keys via mobile data?

### ISSUE THREAD

**Issue by ndegendogo** [corona-warn-app/cwa-website#649]
## Describe the issue

*Hoping that this is the correct context to submit a ticket for your [FAQ](https://www.coronawarn.app/en/faq/#no_risk_update_ios)*

Your current FAQ states
> Important: Mobile/cellular data that are transmitted during the usage of Corona-Warn-App is free of charge and will not be deducted from your data plan!

However, since cwa 1.7 the frequency of DEK key downloads was increased to a 4-hour-schedule.
According to [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/916#issuecomment-734805607)
> the current agreement includes one update per day in the so-called zero rating

Is this true? If yes, the FAQ entry needs to be corrected.

## Suggested change

Clarify which of the conflicting informations is true. Ensure that the FAQ has the latest and true information.

**Comment by Ein-Tim** [comment]
Since hourly keys will only be downloaded if connected to WiFi (because of this agreement), I don't think this needs to be update.
If CWA downloads the one daily key via mobile data, the user will not be charged.

**Comment by dsarkar** [comment]
@ndegendogo, @Ein-Tim 

Does this solve this issue: https://www.coronawarn.app/en/faq/#risk_update_24? Admittedly, there is a lot of information in the FAQs and it is not so easy to put it in an organized way. DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@ndegendogo, and yes, this is the correct place to discuss FAQs. Thanks! DS

**Comment by ndegendogo** [comment]
> Since hourly keys will only be downloaded if connected to WiFi 

Is this really true?
See also [this comment](https://github.com/corona-warn-app/cwa-app-ios/issues/1627#issuecomment-738767326) by @sin-azucar

> apparently it's trying to download **something**

**Comment by dsarkar** [comment]
@ndegendogo, 

- Q: Hourly keys will only be downloaded if connected to WiFi? 
- A: This seems to be the current implementation, however, will bring this question to the developers in order to confirm.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@ndegendogo 
I am 100% sure the App does not download hourly files via Mobile Data. 
See: https://github.com/corona-warn-app/cwa-app-ios/pull/1468#issuecomment-722449837

**Comment by ndegendogo** [comment]
Thanks @dsarkar

**Comment by Ein-Tim** [comment]
@dsarkar 

Did the devs give you an answer?

**Comment by dsarkar** [comment]
@Ein-Tim, @ndegendogo, will come back to you. I think the answer I got  is not directly related to your question. It was confirmed that via mobil data only one update is made per day. Will clarify and re-phrase the question again these days. Thanks for your patience. DS

**Comment by MikeMcC399** [comment]
@ndegendogo 

https://www.coronawarn.app/en/faq/results/#no_risk_update_ios "[Apple/iOS]: My risk status hasn't been updated for over a day. An internet connection was available, what's wrong?" says:

"Important: Mobile/cellular data that are transmitted during the usage of Corona-Warn-App is free of charge and will not be deducted from your data plan!"

---

https://www.coronawarn.app/en/faq/results/#risk_update_24 "How often is the risk status updated?" says:

"Since CWA version 1.7, exposure checks are run up to 6 times per day when a Wi-Fi connection is present. The repeated daily check is performed automatically. While using mobile data, the check is only performed once every 24 hours due to the [zero rating commitment](https://www.coronawarn.app/en/faq/results/#mobile_data_costs) of the network providers."

---
https://www.coronawarn.app/en/faq/results/#mobile_data_costs "When I'm not connected to a Wi-Fi network, will I be charged for any mobile data transmitted via the app?"

confirms all this. In addition @thomasaugsten stated in https://github.com/corona-warn-app/cwa-app-android/issues/4753#issuecomment-1050696149 about 4 weeks ago

"Traffic of the CWA are free of charge on mobile data plans."

---

I can't see any discrepancies. Do you still think that something needs to be changed in the FAQs?

**Comment by ndegendogo** [comment]
@MikeMcC399 you are right. The FAQ has improved a lot since I submitted this ticket.

Closing as resolved.
