### ISSUE TITLE
Screenshot is missing in English blog post about v 1.9

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#684]
## Where to find the issue
https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/

## Describe the issue
[German blog post](https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/) is showing two screenshots (green and red), the English one only shows one (red - green is missing).

## Suggested change
Add green screenshot to https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/.

---
Internal Tracking ID: [EXPOSUREAPP-4364](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4364)

**Comment by dsarkar** [comment]
Dear @Ein-Tim,

Thank you for your contribution.

We have created a ticket for the bug in the internal Jira system. 
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-)

**Comment by MikeMcC399** [comment]
In https://github.com/corona-warn-app/cwa-website/tree/master/blog/2020-12-16-cwa-release-1-9

I would expect to see an image `cwa-low-risk-screenshot-en.jpg` and this is missing.

BTW: the equivalent German image `cwa-low-risk-sreenshot.jpg` has a strange spelling of screenshot. If you are updating the blog you might like to correct his cosmetic point as well.

**Comment by dsarkar** [comment]
@MikeMcC399, you spot everything! ;-) Forwarded!

**Comment by Ein-Tim** [comment]
Will be solved with #696

**Comment by MikeMcC399** [comment]
@Ein-Tim 
There maybe still a problem with the screen shots, but I can't confirm for sure because I have not received Android 1.9.1 yet.

It looks like the German screen shots on https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/ are not from version 1.9.1 because I would expect to see "NÄCHSTE SCHRITTE" instead of "Informieren & helfen" because that is what I see on the Android 1.9.1 RC1. What text do you see on iOS with 1.9.1?

**Comment by Ein-Tim** [comment]
I see "Nächste Schritte" too...
I can't reopen this Issue, so I think best would be if you would open a new one. 
Sorry, have a nice evening 😅

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I can't reopen this Issue, so I think best would be if you open a new one.

I will open a new issue when I have the official final release available and installed. I still can't see it in the Google Play Store.

**Comment by Ein-Tim** [comment]
Thanks @dsarkar

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I opened a new issue https://github.com/corona-warn-app/cwa-website/issues/718 concerning the wrong version of screen shots in the German version of the blog post
https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/

The screen shots in the English version of the blog post https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ are correct.

Since the remaining issue is now described in the new posting https://github.com/corona-warn-app/cwa-website/issues/718, this issue (https://github.com/corona-warn-app/cwa-website/issues/684) can now be closed. Thanks for waiting!
