### ISSUE TITLE
new FAQ item: Probability of false positives and - negatives. 

### ISSUE THREAD

**Issue by dominiklenne** [corona-warn-app/cwa-website#731]
## Feature description

I would suggest a new FAQ entry or an addition to an existing FAQ item with the following information, if available:
1. Average percentage of people with red / green warning messages being infected / not infected.
2. Average percentage of all contacts of an infected person with the app installed and working within the critical period, that have been infected, but get no, or not the red, warning message.

## Problem and motivation

In the FAQ section and some webpages linked to it, the basic algorithm of risk calculation is laid out, which is good. 
There is a some conversation in the internet and elsewhere about the warning app being good for nothing, or even a bad thing. With some scientifically sound statistical data you could give help for propaganda for the app, as well as helping public health pros to assess the effect of the app.

## Is this something you're interested in working on

Yes.

**Comment by Ein-Tim** [comment]
Related/For (more) information see: https://github.com/corona-warn-app/cwa-documentation/issues/394

---

IMHO a FAQ entry about this would make sense, if you want more information now @dominiklenne, please see the linked issue above.

**Comment by MikeMcC399** [comment]
@dominiklenne 
I may have misunderstood your request, but I don't think it is possible to realise it.

The [CWA app Privacy Notice](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf) says:

"The risk of infection is calculated exclusively offline in the app and is not passed on to the
COVID-19 exposure notification system or any other recipient (including the RKI, other health
authorities in Germany or other countries, Apple, Google and other third parties)."

That means only the user of an individual mobile device knows what risk result has been determined and displayed. Since this result is never shared, then there is no possibility to calculate any statistics based on gathering this data from all users.

There are however some statistics published weekly on https://www.coronawarn.app/en/blog/ and on https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html. In addition there is also some on-going community analysis done and shown on https://ctt.pfstr.de/.

**Comment by heinezen** [comment]
Hey @dominiklenne ,

Thanks for your input. As already stated by @MikeMcC399 we cannot retrieve this information because:

* The risk status (red / green) is calculated locally and never shared with the CWA servers
* The app does not necessarily know if a user is infected. This is only known if the user enters their positve test result into the app which is not mandatory

However, information that is known is regularly aggregated on the [RKI website for the CWA](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/WarnApp/Archiv_Kennzahlen/WarnApp_KennzahlenTab.html).

I will close this issue because we cannot make this request happen.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dominiklenne** [comment]
Realizing how really difficult it is to get those data, I'm ok with closing the issue. 
It would be necessary to do elaborate scientific studies to get them, like simulations of virus transmission and bluetooth connection strength for a whole variety of social situations or meticulous reconstruction of many real world infection events. 
Thx for considering anyway.

**Comment by MikeMcC399** [comment]
@dominiklenne 

You can find details of a study from [Fraunhofer IIS](https://www.iis.fraunhofer.de/) on https://github.com/corona-warn-app/cwa-documentation/blob/master/2020_06_24_Corona_API_measurements.pdf.

**Comment by dominiklenne** [comment]
Thx, very interesting. It of course does not give real infection probabilities for the different "buckets".
Taking "ground truth" as the "true" infection probability, the detection of "no exposure" is satisfactory. There are not many false positives, so to say. OTOH, the detection of "exposure" is looking rather blurred with a lot of false negatives.
