### ISSUE TITLE
FAQ - Transnational exposure logging - meaning of date

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-website#767]
## Where to find the issue

- https://github.com/corona-warn-app/cwa-website/pull/764#issuecomment-757153580 
## Suggested change

- also update status date
- Finland not showing up  https://github.com/corona-warn-app/cwa-website/pull/764#issuecomment-757683864

**Comment by dsarkar** [comment]
The date shown is the date when feeding starts.

**Comment by MikeMcC399** [comment]
@dsarkar 
> The date shown is the date when feeding starts.

It makes sense to use this date, because if somebody has visited one of the countries the information tells a user from what date they are potentially covered by Diagnosis Keys from that country. (Of course, for the keys to become usable the country's data also has to be pulled.)

I'm wondering if it is necessary to keep the dates if they are more than 14 days in the past because according to https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf earlier data, also on the EFGS, is deleted after 14 days. So the date becomes irrelevant after 14 days. If the date is within the last 14 days it shows how much of the period is covered by active Diagnosis Keys. I understand though that it is easier just to leave the dates in the list instead of removing them when they are older.

**Comment by MikeMcC399** [comment]
@dsarkar 
Finnland is now showing in the list.

So I think this issue can be closed.

**Comment by MikeMcC399** [comment]
Unfortunately the country name for Finland in the Android app has the German and English renderings the wrong way around. See https://github.com/corona-warn-app/cwa-app-android/issues/2069.

The use of the country name in the FAQs looks correct for English and German though! 👍
