### ISSUE TITLE
FAQ: [Google/Android]: Error when communicating with Google API (39508) - update needed?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#781]
## Where to find the issue
https://www.coronawarn.app/en/faq/#API39508 
[Google/Android]: Error when communicating with Google API (39508)

## Describe the issue
The app no longer outputs the error code 39508 any more. It puts out a text error instead:

<string name="errors_risk_detection_limit_reached_title">"Limit already reached"</string>

<string name="errors_risk_detection_limit_reached_description">"No more exposure checks possible today, as you have reached the maximum number of checks per day defined by your operating system. Please check your risk status again tomorrow."</string>

The whole exposure checking went through a major update with the release of 1.9.1 according to the blog post https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ from Dec 16, 2020.

~~There haven't been any more comments made to the issue https://github.com/corona-warn-app/cwa-app-android/issues/1459 for over 5 weeks.~~ Now closed.
  

## Suggested change
Possibly change the FAQ to say fixed with 1.9.1 ~~and close https://github.com/corona-warn-app/cwa-app-android/issues/1459~~.

Edit:
https://github.com/corona-warn-app/cwa-app-android/issues/1459 was closed on Mar 9, 2021.

**Comment by dsarkar** [comment]
Suggestion:


"

[Google/Android]: Limit already reached (Previously: Error when communicating with Google API (39508))
---

**UPDATE 16.01.2021:**

The notification reads now:

**'Limit already reached**

**No more exposure checks possible today, as you have reached the maximum number of checks per day defined by your operating system. Please check your risk status again tomorrow.'**

The whole exposure checking went through a major update with the release of 1.9.1, see also the blog post https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/ from Dec 16, 2020, and since the release 1.9.1 no more reports on this issue have been submitted.

However, should you experience an issue related to this error notification, please submit your report here: corona-warn-app/cwa-app-android#1459.

---

_... the remainder of the original FAQ entry_
"

**Comment by MikeMcC399** [comment]
@dsarkar 
Since the error message has changed, maybe the title of issue https://github.com/corona-warn-app/cwa-app-android/issues/1459 needs to be changed as well, if the old errors, and any new errors are to be captured in the same issue? The title is currently:
"🔥 Error 39508 after updating to 1.5 or later"

- Since it is not a hot issue any more, the hot issue icon should be removed from the title of https://github.com/corona-warn-app/cwa-app-android/issues/1459. It hasn't been using the hot issue label (as opposed to hot issue icon in the label) for a long time.
- Change the title of https://github.com/corona-warn-app/cwa-app-android/issues/1459 to "Error 39508 / Limit already reached" **or**
- Open a new placeholder issue for any new issues with the new error message "Limit already reached" and then link to the new issue.

**Comment by MikeMcC399** [comment]
@dsarkar 

This issue has become a little up in the air.

https://www.coronawarn.app/en/faq/#API39508
[Google/Android]: Error when communicating with Google API (39508)

still says
"If you are still receiving the error after updating to 1.5 and waiting 24 hours, please report it in the [associated GitHub issue](https://github.com/corona-warn-app/cwa-app-android/issues/1459)".

However, the issue "Error 39508 / Limit already reached" https://github.com/corona-warn-app/cwa-app-android/issues/1459 has now been closed.

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, indeed. I Will definitively try to clean up the website project board these days.

**Comment by MikeMcC399** [comment]
This issue was resolved by #895.
