### ISSUE TITLE
Automated link checking?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#889]
## Your Question

Is there some way to automate checking of links used by https://www.coronawarn.app/ to identify failed links, like the one reported in https://github.com/corona-warn-app/cwa-website/issues/886?

In the [cwa-documentation repository](https://github.com/corona-warn-app/cwa-documentation) there is a check in 
[checks.yml](https://github.com/corona-warn-app/cwa-documentation/blob/master/.github/workflows/checks.yml)
```
      - name: Checking for broken links
        if: always()
        run: |
          npm run-script checklinks
```
unfortunately this can't be taken 1:1 because it only checks markdown files *.md

`    "checklinks": "find . -not -path \"*node_modules*\" -not -path \"*.github*\" -name \"*.md\" | xargs -n 1 markdown-link-check",`

Perhaps there is something similar which could be used on https://www.coronawarn.app/?

**Comment by heinezen** [comment]
[cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) has the advantage that all files are pure static Markdown. For the website, Markdown (blogposts) and JSON files with HTML (FAQ) are compiled into the resulting website, so we might not be able to just check the source files for errors. This would make a solution more complicated. However, we could check the output of the build because that is HTML-only. Not sure how easy this would be.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 

[markdown-link-check](https://www.npmjs.com/package/markdown-link-check) uses
[link-check](https://www.npmjs.com/package/link-check)

so perhaps [link-check](https://www.npmjs.com/package/link-check) could be used for this task?

**Comment by MikeMcC399** [comment]
@dsarkar 
There are major changes to links in the open PR https://github.com/corona-warn-app/cwa-website/pull/1772 for the analysis page.

How can these links be checked to make sure they all work?

**Comment by MikeMcC399** [comment]
Links are still broken, see https://github.com/corona-warn-app/cwa-website/issues/1778.

**Comment by MikeMcC399** [comment]
Closing in favour of feature request https://github.com/corona-warn-app/cwa-website/issues/1781.
