### ISSUE TITLE
Extend `update_iOS` with suggestion what to do if you don‘t want to update iOS

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-website#946]
## Where to find the issue

https://www.coronawarn.app/de/faq/#update_iOS
https://www.coronawarn.app/en/faq/#update_iOS

## Describe the issue

The FAQ entry advices to update the iOS Version in order to continue to use CWA. 

## Suggested change

The FAQ entry should be extended with [this](https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_de) link which gives a overview over all apps in Europe which use the ENF and wether they participate on the Transnational Exposure Logging or not.

Some apps listed there are still using version 1 of the ENF, thus they are available on iOS 13 versions below 13.7.

## Additional Information

~~I will provide a PR later.~~

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I'm not sure that advising users to install an app from another country as a workaround is a good idea!

You might like to gather some feedback here before submitting a PR for that idea.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

What would be the problem in doing this? 

This has been originally proposed by @jucktnicht in https://github.com/corona-warn-app/cwa-app-ios/issues/2032#issuecomment-787409479.

**Comment by MikeMcC399** [comment]
@Ein-Tim

Do you have an example of a country's app which you would like to recommend to iOS users below 13.7?

I would consider a recommendation to use a COVID-19 app from another country in the FAQs of the Corona-Warn-App as an endorsement by the Robert Koch Institute, the publishers of CWA. RKI might not like that, or they might want to see a disclaimer added.

The link you quoted, https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/travel-during-coronavirus-pandemic/mobile-contact-tracing-apps-eu-member-states_de, doesn't give information about whether an app is using v1 or v2.

I don't follow the details of iOS, but Google strongly recommends **against** using v1 mode (see https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes).

The risk calculations will not be up-to-date, not just due to the v1 / v2 difference, but also due to changes based on new patterns of infection like new Variants of Concern which may be handled differently by apps from other countries based on the epidemiological situation in the population of the country where the app comes from.

If an app is currently using v1, do you know if they are frozen into v1 or if they are planning to update to v2?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Do you have an example of a country's app which you would like to recommend to iOS users below 13.7?

No, not really. I wouldn't name one specifically because (what you also pointed out) this could be misunderstood as a endorsement.

> I would consider a recommendation to use a COVID-19 app from another country in the FAQs of the Corona-Warn-App as an endorsement by the Robert Koch Institute, the publishers of CWA. RKI might not like that, or they might want to see a disclaimer added.

I definitely agree with you and (as said above) I would only link to either the link I quoted above or even better to the already existing list in https://www.coronawarn.app/en/faq/#interoperability_countries. 
This would be not the best user experience since the user would have to go ahead and search for the apps of the countries itself, but it wouldn't be an endorsement. 

The next problem is that the user with this approach would have to pick one of the apps and then go into the App Store to see if they are compatible with iOS 13.5 - 13.6.1 (and use v1 of ENF). 

> I don't follow the details of iOS, but Google strongly recommends against using v1 mode 

Apple AFAIK has no (public) recommendation like Google has in the [link](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes) you provided.

> The risk calculations will not be up-to-date, not just due to the v1 / v2 difference, but also due to changes based on new patterns of infection like new Variants of Concern which may be handled differently by apps from other countries based on the epidemiological situation in the population of the country where the app comes from.

This is a good point. I also thought about it, the only thing about this is that we write a disclaimer. 

> If an app is currently using v1, do you know if they are frozen into v1 or if they are planning to update to v2?

I don't know for each country specifically, so yes could be that some are going to update to v2. 

---

Summarized:

I thought to techie about this, for some users it might make sense to install another app, but for the majority of the users the best way is to update to min. iOS 13.7.

I will close this issue now, since @MikeMcC399 showed well that this is not really feasible.
After having a second thought I also think that this would lead to more confusion then help. 

Thanks for the valuable input @MikeMcC399!
